### ISSUE TITLE
cocoapod support

### ISSUE THREAD

**Issue by parthisubu** [DaveWoodCom/XCGLogger#1]
Hey there,

This looks very interesting, would it be possible to add cocoapod support to your logging framework please?

Thanks.

**Comment by skywinder** [comment]
You are not, but what about others?
Will you accept pull request with CocoaPods integration?

**Comment by mihaeu** [comment]
@skywinder Yeah that would be awesome. If you do this in a fork let me know please.

**Comment by DaveWoodCom** [comment]
This is an old, closed issue. CocoaPods as been added to the master branch already.

**Comment by skywinder** [comment]
Thanks!:+1:
