### ISSUE TITLE
Problem linking XCGLogger in a framework when built from Carthage

### ISSUE THREAD

**Issue by carterpayne** [DaveWoodCom/XCGLogger#103]
I have a project with an embedded framework where the framework links XCGLogger that was built from Carthage. When I build my project I get a linking error saying it cannot find XCTest. 
I noticed that building XCGLogger from Carthage it builds schema "XCGLogger (iOS)" with "Release" Configuration. This configuration also builds the XCGLoggerTests target as well. So when I build my project it thinks I need to link XCTest as well

Could it either having a prebuilt framework for carthage, or remove building the test framework from that schema?

**Comment by DaveWoodCom** [comment]
I believe this is now fixed. Please reopen if the issue occurs again. Thanks.
