### ISSUE TITLE
Linker error when adding XCGLogger.swift file to Xcode project

### ISSUE THREAD

**Issue by PaulDapolito** [DaveWoodCom/XCGLogger#104]
When I add the XCGLogger.swift file to my Xcode project and import the module in AppDelegate.swift, I cannot build with the following error:

    ld: framework not found XCTest for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by DaveWoodCom** [comment]
I believe this is fixed now (dup of #103). Please reopen if the issue occurs again. Thanks.
