### ISSUE TITLE
Log color doesn't work.

### ISSUE THREAD

**Issue by hhgz9527** [DaveWoodCom/XCGLogger#106]
![screen shot 2015-11-17 at 4 05 49 pm](https://cloud.githubusercontent.com/assets/7303158/11205773/4473a840-8d45-11e5-8658-170ec13184f8.png)

Hi,

I use this 3.0 version, log color not work.

My Xcode version: 7.1
My OS X version: 10.11.1

**Comment by DaveWoodCom** [comment]
You need to install the XcodeColors plug in.

https://github.com/robbiehanson/XcodeColors
