### ISSUE TITLE
Question about File logging

### ISSUE THREAD

**Issue by vittoriom** [DaveWoodCom/XCGLogger#107]
We're using `XCGLogger` for our app and would like to send log files to HockeyApp as additional data we can use to debug our crashes. 

We have some concerns though:

- As soon as the app is started (even after a crash) the log file is overwritten, there is no append support and we have to manually "roll" the file by renaming it and delaying its deletion for the Hockey manager to send it to the backend.
- As far as I can see, writing to the file is not async, this means that we are actually slowing down the app when logging, which is suboptimal

Apart from this, I was wondering if there is any specific reason why `XCGBaseLogDestination` isn't a protocol? After all, `output` has a `precondition` inside because the class can't exist by itself, so it could make more sense to have it as a protocol and through extensions implement `processLogDetails`, `processInternalLogDetails` and `isEnabledForLogLevel`

Thanks!

**Comment by DaveWoodCom** [comment]
Hi @vittoriom,

I've just pushed an update that gives you the option to write the log file in the background. Please take a look at the updated Readme for details on how to do it now.

Adding a rolling log is on my list to add (should be next).

Regarding the log destination protocol issue, `XCGLogDestinationProtocol` is the protocol I'm using to define the minimum requirements a log destination needs. `XCGBaseLogDestination` includes a few extra bits that other destinations may not need. I'd probably do it a little differently if I was creating it from scratch now, but want to avoid making changes that would break other projects that now rely on the current code.

**Comment by DaveWoodCom** [comment]
Have added a basic log rotation method, see #69.
