### ISSUE TITLE
Integrating with UI Testing - XCTest

### ISSUE THREAD

**Issue by createdon2003** [DaveWoodCom/XCGLogger#110]
Hi

I am trying to use your framework as logger in our testing framework. But when I am trying to log to file I get error stating "Attempt to open log file for writing failed: Optional("The operation couldn’t be completed. (Cocoa error 2.)")"

There is no AppDelegate file in testing App generated by UI testing framework.

Thanks
Naveen

**Comment by DaveWoodCom** [comment]
Hi @createdon2003,

This is probably a question you'd want to ask on [StackOverflow](http://stackoverflow.com/questions/tagged/xcglogger) as you'd likely get an answer sooner (and everyone watching the repo wouldn't be notified unnecessarily).

That error message points to it being a problem with the path you're trying to write to. Does the folder exist? Do you have write permission?
