### ISSUE TITLE
Is it just me, or is XCGLogger segfaulting the compiler a lot?

### ISSUE THREAD

**Issue by CSchwang** [DaveWoodCom/XCGLogger#112]
Hi,

I noticed that XCGLogger triggers compiler bugs quite often for me
Even something as simple as:
    let someString = "asd"
    log.debug(someString.debugDescription)
seems to segfault.

Not really an Issue with XCGLogger, but I wanted to know, whether that's just my system or if anyone can reproduce it.

**Comment by DaveWoodCom** [comment]
This does cause the compiler to segfault. It's related to issue #80. The simple fix is to use string interpolation:

`log.debug("\(someString.debugDescription)")`
