### ISSUE TITLE
Debug coloring not working

### ISSUE THREAD

**Issue by patchthecode** [DaveWoodCom/XCGLogger#115]
After installing the coloring addon https://github.com/robbiehanson/XcodeColors
The coloring works if i open the https://github.com/robbiehanson/XcodeColors sample project. But your XCGLogger still has no color

**Comment by DaveWoodCom** [comment]
Did you enable colour on your log object?

    log.xcodeColorsEnabled = true

**Comment by patchthecode** [comment]
oh my word... i  guess i missed that one. Thanks for the help. It works now.
