### ISSUE TITLE
Ability to log without parameters (i.e. `log.info()`)

### ISSUE THREAD

**Issue by dusek** [DaveWoodCom/XCGLogger#118]
`XCGLogger` already outputs lots of information by default that help identify in which part of the app the message takes place – mainly filename, line number and mostly function name.

Sometimes one wants to just log that a certain function has been called (i.e. when logging user interface actions like switching tabs in `UITabBarController`, or `viewWillAppear`/`viewWillDisappear`.) In this case,  I use `log.info("")` as the default message fully suffices in lot of cases (it does not suffice only when I want to add some details, but that is not always the case).

So I would rather write `log.info()` instead of `log.info("")` in such case.

**Comment by bobringer** [comment]
For what it's worth... I do the exact same thing (and funny enough, these are the primary examples of when I use it).  I tend to do it with "verbose" so I can turn off this sort of tracing easily, but it would be nice if the API was friendly to those of us who want to know "I got here"

**Comment by JaviSoto** [comment]
What I did was to add an extension method to XCGLogger called trace, so that I could do:

log.trace()

And optionally:

log.trace(logLevel: .Info)

**Comment by DanielAsher** [comment]
I've added #121 that addresses this issue.

**Comment by dusek** [comment]
@DanielAsher thanks for letting us know and for the PR!

**Comment by dusek** [comment]
This is now solved in the recent versions (tested e.g. with 3.5.1). Thanks!
