### ISSUE TITLE
output appended by "[;"

### ISSUE THREAD

**Issue by PeerLabs** [DaveWoodCom/XCGLogger#119]
Is it just me that something i am doing wrong... but every output gets suffixed with "[;"in the console .. but the file seems ok...

[DEBUG_Log.txt](https://github.com/DaveWoodCom/XCGLogger/files/117654/DEBUG_Log.txt)

Sample console Output:
[fg0,128,0;[bg;2016-02-05 01:02:00.783 [Info] > esalahadmin Version: 1.0 Build: 1 PID: 12546[;
[fg0,128,0;[bg;2016-02-05 01:02:00.783 [Info] > XCGLogger Version: 3.2 - LogLevel: Debug[;
[fg0,128,0;[bg;2016-02-05 01:02:00.817 [Info] > XCGLogger writing to log to: file:///Users/abrarpeer/Library/Developer/CoreSimulator/Devices/6E79EC66-E23E-4125-8725-8FB3A6959072/data/Containers/Data/Application/1DC3BC1E-DC7E-40B5-AA46-A22B9559CDF7/Library/Caches/DEBUG_Log.txt[;
[fg169,169,169;[bg;2016-02-05 01:02:00.817 [Debug] [main] [MainTabBarController.swift:27] viewDidLoad() > Started![;
[fg169,169,169;[bg;2016-02-05 01:02:00.818 [Debug] [main] [MainTabBarController.swift:33] viewDidLoad() > Finished![;
[fg169,169,169;[bg;2016-02-05 01:02:00.878 [Debug] [main] [MainTabBarController.swift:39] viewDidAppear > Started![;
[fg169,169,169;[bg;2016-02-05 01:02:00.898 [Debug] [main] [LoginViewController.swift:18] viewDidLoad() > Started![;
[fg169,169,169;[bg;2016-02-05 01:02:00.898 [Debug] [main] [LoginViewController.swift:39] setupBackgroundImageView() > Started![;
[fg169,169,169;[bg;2016-02-05 01:02:00.901 [Debug] [main] [LoginViewController.swift:46] setupBackgroundImageView() > bgImage = <UIImage: 0x7fbc4adb7600>, {375, 667}[;
[fg169,169,169;[bg;2016-02-05 01:02:00.902 [Debug] [main] [LoginViewController.swift:47] setupBackgroundImageView() > bgImage Size = (375.0, 667.0)[;
[fg169,169,169;[bg;2016-02-05 01:02:00.902 [Debug] [main] [LoginViewController.swift:54] setupBackgroundImageView() > bgImageView = <UIImageView: 0x7fbc4ae04960; frame = (0 0; 375 667); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7fbc4ae04830>>[;
[fg169,169,169;[bg;2016-02-05 01:02:00.903 [Debug] [main] [LoginViewController.swift:55] setupBackgroundImageView() > bgImageView Frame = (0.0, 0.0, 375.0, 667.0)[;
[fg169,169,169;[bg;2016-02-05 01:02:00.903 [Debug] [main] [LoginViewController.swift:56] setupBackgroundImageView() > bgImageView Bounds = (0.0, 0.0, 375.0, 667.0)[;
[fg169,169,169;[bg;2016-02-05 01:02:00.904 [Debug] [main] [LoginViewController.swift:62] setupBackgroundImageView() > Finished![;
[fg169,169,169;[bg;2016-02-05 01:02:00.904 [Debug] [main] [LoginViewController.swift:68] setupLogoView() > Started![;
[fg169,169,169;[bg;2016-02-05 01:02:00.905 [Debug] [main] [LoginViewController.swift:77] setupLogoView() > Finished![;
[fg169,169,169;[bg;2016-02-05 01:02:00.905 [Debug] [main] [LoginViewController.swift:29] viewDidLoad() > Finished![;
[fg169,169,169;[bg;2016-02-05 01:02:00.906 [Debug] [main] [MainTabBarController.swift:51] viewDidAppear > Finished![;

**Comment by DaveWoodCom** [comment]
You have XcodeColors enabled, but not installed. Either install the plug-in from here: https://github.com/robbiehanson/XcodeColors or disable colour by setting `xcodeColorsEnabled` to `false` (or most likely remove the line setting it to `true`)

**Comment by PeerLabs** [comment]
Thanks! Worked like a charm!
