### ISSUE TITLE
Add addMinLevelFilter functionality to override log level for files and functions matching filter pattern.

### ISSUE THREAD

**Issue by DanielAsher** [DaveWoodCom/XCGLogger#120]
Thanks for this great logging framework!

[SwiftyBeaver](https://github.com/SwiftyBeaver/SwiftyBeaver) has a nice feature that allows overriding the log level for folders/files/functions that match a pattern. You can see this [here](https://github.com/SwiftyBeaver/SwiftyBeaver/blob/04667d1e6cedd51140e34128754a589ce7da6239/sources/BaseDestination.swift#L156).

I use multiple logs (like many others) which SwiftyBeaver does not support. It would be great to see `addMinLevelFilter` functionality added to XCGLogger :)

**Comment by DaveWoodCom** [comment]
Check out the filter options in the https://github.com/DaveWoodCom/XCGLogger/tree/swift_3.0 branch. Think you'll like it much better. Let me know if there's something our filters can't do that you need.
