### ISSUE TITLE
Verbose logging during application launch is suppressed.

### ISSUE THREAD

**Issue by dtrenz** [DaveWoodCom/XCGLogger#128]
Because `.Debug` is the default log level, any logging via `log.verbose()` that occurs before `application:didFinishLaunchingWithOptions:`/`applicationDidFinishLaunching:` is called will not be output to any output destination.

For example, if the AppDelegate looks like this;

```swift
@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {

    func applicationDidFinishLaunching(aNotification: NSNotification) {
        log.setup(
            .Verbose,
            showThreadName: true,
            showLogLevel: true,
            showFileNames: true,
            showLineNumbers: true,
            writeToFile: nil,
            fileLogLevel: nil
        )
    }

}
```

...and the initial View Controller looks like this;

```swift
class ViewController: NSViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        log.verbose("This message will not be output to console.")
    }

}
```

The verbose log message will not be output to the console because `viewDidLoad` on the initial view controller is called before the `log.setup()` method is called in the AppDelegate, which lowers the log level from `.Debug` (default) to `.Verbose`.

If I could think of a good way to solve this, I would submit a PR instead of an issue. :smile:

**Comment by DaveWoodCom** [comment]
Hmm, `didFinishLaunching...` should be called before `viewDidLoad` unless you have an unusual set up.

In any case, if you're seeing that happen, you could change your `log` configuration to something like the sample below in order to ensure it's configured before being used.

```swift
let log: XCGLogger = {
    let log = XCGLogger.defaultInstance()
    log.setup(.Verbose, showThreadName: true, showLogLevel: true, showFileNames: true, showLineNumbers: true)

    return log
}()
```
