### ISSUE TITLE
Use StaticString for functionName and fileName

### ISSUE THREAD

**Issue by Zyphrax** [DaveWoodCom/XCGLogger#130]
I was looking at your library because I use CocoaLumberjack in my project and their Swift support feels a bit hackish. However I did notice a hidden gem.

They define functionName and fileName as [StaticString](https://developer.apple.com/library/ios/documentation/Swift/Reference/Swift_StaticString_Structure/index.html) instead of String. By using StaticString you're telling the compiler that the string values can be determined at compile time, allowing the compiler to optimize the statements.

So for example:
```
public func info(@autoclosure closure: () -> String?, 
  functionName: String = #function, fileName: String = #file,
  lineNumber: Int = #line)
```
would become
```
public func info(@autoclosure closure: () -> String?,
  functionName: StaticString = #function, fileName: StaticString = #file,
  lineNumber: Int = #line)
```

A nice way to squeeze even a bit more performance out of it.

Another tip: in my implementation I'm using `Any?` instead of `String?` as the item to log. That way you can easily log integers, enums, custom classes etc. Simply convert the value to String as late as possible by calling `String(closure())`. That way it works similar to the `print` command.

**Comment by DaveWoodCom** [comment]
Thanks. Have changed to StaticString.

**Comment by Zyphrax** [comment]
Thanks for changing that!

Did you also see the `Any?` instead of `String?` thing?
`@autoclosure closure: () -> String?` to `@autoclosure closure: () -> Any?`

That makes the logger even more flexible to use.

**Comment by DaveWoodCom** [comment]
I did. I have another ticket tracking that as well. It will likely be pushed into the Swift 3.0 branch that I should be pushing soon.

**Comment by Zyphrax** [comment]
Ok great, thanks!

**Comment by DaveWoodCom** [comment]
Ok, squeezed this in for the Swift 2.2 as well. Thanks!
