### ISSUE TITLE
Log duration

### ISSUE THREAD

**Issue by andreabozza1984** [DaveWoodCom/XCGLogger#132]
Hello,
 I miss the way to set the duration of stored log file.
This option exist or it will be implemented?
I want avoid to store inside the device a large amount of bytes inside log file
thank
Andrea

**Comment by DaveWoodCom** [comment]
Hi @andreabozza1984, this isn't handled by the library (at least not yet). Your app would be responsible for managing it's own files once created. Also, you'd want to store the file inside the app's caches folder, not inside the documents folder to avoid the file being backed up to iCloud (Apple may reject your app for that).
