### ISSUE TITLE
swift 3 archiving project error

### ISSUE THREAD

**Issue by InnaLMC** [DaveWoodCom/XCGLogger#147]
When I archive project I got an error about <Cocoa/Cocoa.h> not found.  Please use something like this 

#if TARGET_OS_IOS
#import \<UIKit/UIKit.h\>
#elif TARGET_OS_WATCH
#import \<WatchKit/WatchKit.h\>
#elif defined(__MAC_OS_X_VERSION_MIN_REQUIRED)
#import \<Cocoa/Cocoa.h\>
#endif

instead of

#import \<Cocoa/Cocoa.h\>

in XCGLogger.h

**Comment by DaveWoodCom** [comment]
Are you using CocoaPods?

It seems to be trying to load all three `XCGLogger.h` files for all platforms, ignoring the settings in the original project that have a specific header file for the specific targets. Looks like a bug in CocoaPods, but I can add the workaround in the next beta.

**Comment by InnaLMC** [comment]
Yes. It'll be helpful, thanks

**Comment by Zyphrax** [comment]
Yes it seems to include a XCGLogger.h for all platforms.
For now I'll just delete the Apple Watch and macOS header files.

![image](https://cloud.githubusercontent.com/assets/966500/18414428/5353cfb2-7795-11e6-8d62-cb9cf0ec4133.png)

**Comment by DaveWoodCom** [comment]
Fixed in 4.0.0-beta.3
