### ISSUE TITLE
Calling XCGLogger.logln directly

### ISSUE THREAD

**Issue by emovla** [DaveWoodCom/XCGLogger#152]
Hi,
I used to call XCGLogger.logln directly from a wrapper of another (C++) logging library.
But now when its arguments are of StaticString type and I can't call it any more passing my String arguments, as it seems impossible to convert from String to StaticString.
(XCGLogger 3.5.1)
Any suggestions what can be done?

**Comment by DaveWoodCom** [comment]
@emovla Can you send me a small sample project? Though, since using StaticString was just supposed to be a performance tweak, it may be easier to just change back to String.

**Comment by emovla** [comment]
Well entire project will be difficult as this is called from C++ code, but the essense is I’m passing the original file and line from the C++ logging macros into this wrapper class that calls XCGLogger:

@objc class LoggerWrapper : NSObject {
   private let logger = XCGLogger.defaultInstance()

   func log(message: String, fileName: String, line: Int32, severity: BWNLogLevel) {
      var xlevel: XCGLogger.LogLevel
      switch (severity) {
      case BWNLogLevel.Verbose: xlevel = .Debug
      case BWNLogLevel.Info: 	xlevel = .Info
      case BWNLogLevel.Warn: 	xlevel = .Warning
      case BWNLogLevel.Error: 	xlevel = .Error
      default:
         xlevel = .Warning
      }
      
      self.logger.logln(xlevel, functionName: "", fileName: "", lineNumber: Int(line), closure: { return message })
   }
}

Cheers, Emil

**Comment by DaveWoodCom** [comment]
I've pushed an update that should solve this for you. Right now it's on the master branch only. I'll have to add it to the swift_3.0 later. For some reason CocoaPods is having issues and won't lint the podspec. I have to crash for a bit and then will come back and figure that out...

**Comment by emovla** [comment]
Many thanks
Emil

**Comment by dusek** [comment]
> I've pushed an update that should solve this for you. Right now it's on the master branch only. I'll have to add it to the swift_3.0 later. For some reason CocoaPods is having issues and won't lint the podspec. I have to crash for a bit and then will come back and figure that out...

@DaveWoodCom just a desperate attempt without looking into details - perhaps it is related to [CocoaPods#5841: Fix linting on Xcode 8](https://github.com/CocoaPods/CocoaPods/pull/5841)? Maybe adding a `.swift-version` file with `3.0` contents could fix this? Just brainstorming loud without understanding any of this, please take with a grain of salt 😄

**Comment by DaveWoodCom** [comment]
This is now on the swift_3.0 branch.

@dusek And for the record, the linting issue was just me being tired and forgetting to change the podspec to include the Objective-C files.
