### ISSUE TITLE
Issues installing 4.0.0 - An unexpected version directory `DemoApps` was encountered

### ISSUE THREAD

**Issue by JALsnipe** [DaveWoodCom/XCGLogger#153]
I'm having some issues installing the 4.0 release tag for Swift 3.

I've added:
```
source 'https://github.com/DaveWoodCom/XCGLogger'
```

to the top of my Podfile and 

```
'XCGLogger', '~> 4.0.0-beta.4'
```

as a dependency.  Here is my log:

```
➜  Example git:(master) ✗ pod update
Update all pods
Re-creating CocoaPods due to major version update.
Updating local specs repositories

CocoaPods 1.1.0.rc.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.2

Analyzing dependencies
[!] An unexpected version directory `DemoApps` was encountered for the `/Users/jal/.cocoapods/repos/davewoodcom/XCGLogger` Pod in the `XCGLogger` repository.
```

**Comment by DaveWoodCom** [comment]
I don't recognize the format you're using for the podfile there. Can you include the whole thing?

Alternately, try using:

Something like this one (will need to be tweaked for your project of course):

```
platform :ios, '9.0'

target 'TestApp' do
	use_frameworks!

	pod 'XCGLogger', :git => 'https://github.com/DaveWoodCom/XCGLogger.git', :branch => ‘swift_3.0’
end
```

Also, you will need to update your CocoaPods binary using something like `sudo gem update cocoapods --pre` to get the latest version. Which is required for Xcode 8 and Swift 3.

**Comment by DaveWoodCom** [comment]
Assuming this is resolved...

**Comment by JALsnipe** [comment]
Sorry for the lack of info, I was declaring this as a dependency in a podspec file.  Haven't tested byt should be all good.  Thank you!

**Comment by DaveWoodCom** [comment]
Ah, ok. If it's a public project, please let me know which one. I haven't tested having XCGLogger as a dependancy in another framework, so I could use yours for that testing.

Thanks.

**Comment by JALsnipe** [comment]
It's a private project.  I initially started migrating all of my project's dependencies over to Swift 3 on release day but decided to hold off another week or two while everyone starts to move over to Swift 3.

**Comment by DaveWoodCom** [comment]
Ok. Definitely let me know if you have any issues.
