### ISSUE TITLE
firelog outdated

### ISSUE THREAD

**Issue by guillaumenel** [DaveWoodCom/XCGLogger#154]
Would you kindly remove firelog as an supported, since it's documentation is sparse and doesn't work with latest sdk. 
Will hopefully save a future developer an hour or so, thinking this is the way to log via firebase.

**Comment by DaveWoodCom** [comment]
Thanks for the note. I've never used Firebase so hadn't tested that. I've removed it for now. Will look into adding an official destination for Firebase at some point.
