### ISSUE TITLE
Swift 2.3 Cocoapods

### ISSUE THREAD

**Issue by luugiathuy** [DaveWoodCom/XCGLogger#155]
Hi! Any expected release date of the `swift_2.3` branch to Cocoapods? Thank you!

**Comment by DaveWoodCom** [comment]
So long as nothing blow's up with the swift_3.0 branch updates I just pushed up, I should be doing official releases for 2.3 and 3.0 later today (giving at least some time for people to report issues).

**Comment by DaveWoodCom** [comment]
Pushed this up. Let me know if you have issues (since 4.0.0) went up shortly after.
