### ISSUE TITLE
Slow compilation for XCGLogger.swift (v3)

### ISSUE THREAD

**Issue by technicalflaw** [DaveWoodCom/XCGLogger#156]
I'm having trouble with slow compilation times with Swift (version 3), and one (of many) causes seems to be `processLogDetails` in `XCGLogger.swift`.

In particular, the `showFileName:117` formatted as follows...

```
extendedDetails += [
    "[",
    (logDetails.fileName as NSString).lastPathComponent,
    showLineNumber ? ":\(logDetails.lineNumber)" : "",
    "] "
].joined()
```

...decreases compilation time from 200ms to 15ms. The line number formatting seems to be the specific issue. (I assume swift's type inference is getting confused).

**Comment by technicalflaw** [comment]
Scratch that, I must have been using an older version of the swift-3 branch. Same situation, but the code is now in `BaseDestination.swift:116`

**Comment by DaveWoodCom** [comment]
I'm not really too worried about compile time. Run time is always the priority. However, that change does speed up runtime a tiny bit as well.

This `extendedDetails += "[\((logDetails.fileName as NSString).lastPathComponent) \((showLineNumber ? ":" + String(logDetails.lineNumber) : ""))] "` seems to speed up run time quite a bit. I just have to double check the memory leak that existed in Swift 2.2 hasn't re appeared.

How does changing the line to that affect your compile time?

**Comment by technicalflaw** [comment]
It's part of quite a large app in which compilation time was getting achingly slow, so i'm working through the biggest bottlenecks, so it's hard to quantify out of context. I've been seeing compilation times of some of my functions going from ~2s down to ~10ms, and almost always involves implicitly typed properties, closures, or multidimensional arrays.

As for numbers, this is before (2015 rMBP)
```
206.7ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:74:15	open func process(logDetails: LogDetails)
205.3ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:74:15	open func process(logDetails: LogDetails)
41.9ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:55:9	get {}
39.9ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:55:9	get {}
2.2ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:145:15	open func processInternal(logDetails: LogDetails)
2.1ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:145:15	open func processInternal(logDetails: LogDetails)
1.7ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:183:15	open func isEnabledFor(level: XCGLogger.Level) -> Bool
1.4ms	<invalid loc>	get {}
1.4ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:183:15	open func isEnabledFor(level: XCGLogger.Level) -> Bool
```

and this is after
```
33.6ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:55:9	get {}
31.0ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:55:9	get {}
30.5ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:74:15	open func process(logDetails: LogDetails)
28.8ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:74:15	open func process(logDetails: LogDetails)
2.1ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:145:15	open func processInternal(logDetails: LogDetails)
2.0ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:145:15	open func processInternal(logDetails: LogDetails)
1.7ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:183:15	open func isEnabledFor(level: XCGLogger.Level) -> Bool
1.7ms	/Users/sos/Documents/Code/Development Pods/XCGLogger/Sources/XCGLogger/Destinations/BaseDestination.swift:183:15	open func isEnabledFor(level: XCGLogger.Level) -> Bool
```

I think the actual issue is the inference when the string is being appended to rather than the  formatting method of the element. i.e.

~200ms: 
```extendedDetails += "[" + (logDetails.fileName as NSString).lastPathComponent + (showLineNumber ? ":" + String(logDetails.lineNumber) : "") + "]```

~70ms: 
```extendedDetails += "[" + (logDetails.fileName as NSString).lastPathComponent + (showLineNumber ? ":\(logDetails.lineNumber)" : "") + "] "```

~30ms:
```
extendedDetails += [
    "[",
    (logDetails.fileName as NSString).lastPathComponent,
    (showLineNumber ? ":" + String(logDetails.lineNumber) : ""),
    "] "
].joined()
```
~30ms:
```
extendedDetails += [
    "[",
    (logDetails.fileName as NSString).lastPathComponent,
    (showLineNumber ? ":\(logDetails.lineNumber)" : ""),
    "] "
].joined()
```

I haven't profiled its run-time performance either, so you might need to take that into account. As you say it's not a major bottleneck, but it's nice to eliminate it. More info on the compilation profiling method can be found [here](http://irace.me/swift-profiling). And thanks for the excellent project, it's become a staple of my dev environment.

**Comment by DaveWoodCom** [comment]
@technicalflaw I've pushed the final 4.0.0 version. Let me know how the latest changes affect your times. I did make some changes, but focused on reducing memory and increasing speed during run time.
