### ISSUE TITLE
[feature] Add possibility to override `logln(...)` functions by subclassing XCGLogger

### ISSUE THREAD

**Issue by ryancrunchi** [DaveWoodCom/XCGLogger#158]
Hi,

From my SO question [here](http://stackoverflow.com/q/39570842/4392254), I was facing a problem when I needed to modify the message for all logs.

I finally found a [solution](http://stackoverflow.com/a/39571683/4392254). But the problem still remains when you subclass XCGLogger, maybe for other purpose.

**Comment by DaveWoodCom** [comment]
I've answered your SO question. Hope that's clear. And I'll add the original feature request, for the prefix soon.

**Comment by DaveWoodCom** [comment]
I've added the feature for you that lets you add a prefix and/or postfix to all log messages. Take a look here for an example: https://github.com/DaveWoodCom/XCGLogger/blob/master/DemoApps/iOSDemo/iOSDemo/AppDelegate.swift#L64
