### ISSUE TITLE
Does XCGLogger have colors title actions?

### ISSUE THREAD

**Issue by kevinlee85** [DaveWoodCom/XCGLogger#161]
I see other libraries are using emoji  to replace the colors feature as below link?

https://github.com/robbiehanson/XcodeColors/issues/88

Can I do the same thing on XCGLogger?

**Comment by DaveWoodCom** [comment]
Yes. See here for a demo of how to set it up: https://github.com/DaveWoodCom/XCGLogger/blob/master/DemoApps/iOSDemo/iOSDemo/AppDelegate.swift

**Comment by kevinlee85** [comment]
Excellent demo, Thank you.

**Comment by hdsenevi** [comment]
Hi @DaveWoodCom, 

I'm interested in using this emoji replacement. But I'm using Swift 2.3 version (XCGLogger 3.6.0). Is there anyway to get this to work in the above mentioned XCGLogger version. Thanks.
