### ISSUE TITLE
didSet for writeToFileURL is not called

### ISSUE THREAD

**Issue by xyzisinus** [DaveWoodCom/XCGLogger#162]
See https://bugs.swift.org/browse/SR-1118

This is not a big deal because the didSet for "owner" also calls openFile().  I just use the issue to let you know.  I found this out while adding the auto file rotation feature.  Will send a pull request when I'm done.

**Comment by DaveWoodCom** [comment]
True. The didSet should be called if the property is set at some other point (after the init), by a sub class or whatever.
