### ISSUE TITLE
Swift Package Manager usage

### ISSUE THREAD

**Issue by genedelisa** [DaveWoodCom/XCGLogger#165]
I'm trying to use this via the SPM. (via Xcode 8)

Here is my Package.swift

```
let package = Package(
    name: "MyFrobs",
    targets: [],
    dependencies: [
           .Package(url: "https://github.com/DaveWoodCom/XCGLogger",
                 majorVersion: 4)
    ]
)


```

I also tried:

```
 .Package(url: "https://github.com/DaveWoodCom/XCGLogger",
                 versions: Version(4,0,0)..<Version(4,0,0))
```

SPM responds to swift package fetch with this:

No version tag found in (pathToMyProject/Packages/XCGLogger) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"

So, I went into the dir for XCGLogger and did a git tags.
... deletia
Version_3.6.0
Version_4.0.0
...

Looks like SPM likes semantic versioning but only tags like 4.0.0 or 3.6.0.
FIne. I added a the 4.0.0 tag in my local repo

swift package fetch

HEAD is now at 636e042 Merge branch 'swift_3.0'
Resolved version: 4.0.0
error: the module at Sources/XCGLoggerTests has an invalid name ('XCGLoggerTests'): the name of a non-test module has a ‘Tests’ suffix
fix: rename the module at ‘Sources/XCGLoggerTests’ to not have a ‘Tests’ suffix

Just an FYI. 
My ego won't be bruised in you tell me I'm doing it wrong. (Just tell me the right way to use it via SPM).

**Comment by wadetregaskis** [comment]
There's more needed than that.  I got it working in my own [hopefully temporary] fork, https://github.com/wadetregaskis/XCGLogger, and have started a pull request (#173) to merge the support back into Dave's master.

**Comment by DaveWoodCom** [comment]
I've pushed @wadetregaskis' Swift Package Manager work up (on develop right now, will hit master soon). And I've added new tags for every version prior. Please let me know if everything is working now as expected.

**Comment by DaveWoodCom** [comment]
This is now on master (5.0.1). Please let me know if you have any issues.
