### ISSUE TITLE
XCGLogger will overwrite log file

### ISSUE THREAD

**Issue by ruixingchen** [DaveWoodCom/XCGLogger#167]
I init a XCGLOgger with this:
```
let cachePaths = NSSearchPathForDirectoriesInDomains(.cachesDirectory, .allDomainsMask, true)
            var logPath:String?
            if cachePaths.count != 0 {
                logPath = cachePaths[0] + "/xlog.log"
            }
            log.setup(level: .verbose, showLogIdentifier: true, showFunctionName: true, showThreadName: true, showLevel: true, showFileNames: true, showLineNumbers: true, showDate: true, writeToFile: logPath, fileLevel: .debug)
log.debug("app launched")
```
and I find that every time my app launched, xlog.log only contains log after "app launched", earlier log disappeared

**Comment by DaveWoodCom** [comment]
@ruixingchen Log rotation is available as an option. See here: https://github.com/DaveWoodCom/XCGLogger#log-file-rotation

You need to use the advanced configuration and set the option on the `FileDestination`. See here for sample code that does it: https://github.com/DaveWoodCom/XCGLogger/blob/master/DemoApps/OSXDemo/OSXDemo/AppDelegate.swift
