### ISSUE TITLE
XCGLogger v3.6 not writing to XCode8's Device log.

### ISSUE THREAD

**Issue by iad24** [DaveWoodCom/XCGLogger#168]
I testing in my app in device with iOS10 in adhoc building.
Then I go to XCode's devices to check on the logs.
But its not there.

I already added this line in my code:
let systemLogDestination = XCGNSLogDestination(owner: XCGLogger.defaultInstance(), identifier:"advancedLogger.systemLogDestination")
        log.addLogDestination(systemLogDestination)

**Comment by DaveWoodCom** [comment]
Two possibilities I see.

a) did you set the `log` variable to `XCGLogger.defaultInstance()`? If not, you're `owner` and `log` object are different. Try setting the `owner` to `log` instead.

b) Did you follow the tip here: https://github.com/DaveWoodCom/XCGLogger#disable-xcodes-log-noise to cut out the extra log noise in Xcode 8? If so, that disables all `NSLog` calls which is what the `XCGNSLogDestination` uses. Disable or remove the `OS_ACTIVITY_MODE` environment variable to restore `NSLog` functionality.

**Comment by iad24** [comment]
a) log and XCGLogger.defaultInstance() are the same
My full code is:
let log =  XCGLogger.defaultInstance()
let systemLogDestination = XCGNSLogDestination(owner:log, identifier:"advancedLogger.systemLogDestination")
log.addLogDestination(systemLogDestination)

b. I did not set that OS_ACTIVITY_MODE, so I should be able to see the NSLogs.

**Comment by DaveWoodCom** [comment]
Do you see the logs when running directly in Xcode (still via the devices screen)? Is it possible you've turned off logging for the `Release` configuration, which is probably set for your ad hoc build? Try changing your ad hoc to use the `Debug` configuration.
