### ISSUE TITLE
Add method to flush log file

### ISSUE THREAD

**Issue by zakkhoyt** [DaveWoodCom/XCGLogger#170]
I'm using XCGLogger as a file logger. Inside my app there is a table which lists all the log files on the disk and allows them to be shared/forwarded. A lot of the time when a user shares the log file, it is not current (the last N logs have not been written to the file yet). I've looked through the API for a way flush, but I see nothing. 

In the mean time I'm removing the current FileDestination then adding a new one. This is less than ideal as there are now multiple files per app session. 

I recommend adding such a method. 

Please advise if I've overlooked something.

**Comment by Zyphrax** [comment]
In my pull request https://github.com/DaveWoodCom/XCGLogger/pull/181, I've added a method `executeWhileSuspended` to the FileDestination which forces the NSFileHandle to write all data that is still memory to disk. Perhaps that will help you out.

**Comment by zakkhoyt** [comment]
Great. I'll check it out. I created my own solution when I opened the ticket and can't recall how I did it. 

- Zakk

**Comment by DaveWoodCom** [comment]
This is now in the 5.0.1 version. It uses @Zyphrax's method basically, though I renamed it to simply 'flush'.
