### ISSUE TITLE
Feature Request: Emojify logs

### ISSUE THREAD

**Issue by rjchatfield** [DaveWoodCom/XCGLogger#171]
Since Xcode 8, we've missed coloured output. It would be great to prepend a message with a string for us to identify different log levels easier (eg. with emoji).

Suggested API:

```swift
log.setup(level: .error, prependedString: "💩")
```

**Comment by justinvallely** [comment]
I think a cleaner implementation would be on the "log-level" level. (That sounds weird.) Then all logs would be prepended with an emoji without changing the interface. 

example: 
log.info("some info message here") would be prepended with an ❤️ be default
log.error("some error message here") would be prepended with an 💩 be default
etc.

**Comment by rjchatfield** [comment]
I just found `PrePostFixLogFormatter` does exactly this https://github.com/DaveWoodCom/XCGLogger/blob/master/Sources/XCGLoggerTests/XCGLoggerTests.swift#L544. 

I'll close this issue. Thanks.

**Comment by justinvallely** [comment]
Fantastic find @rjchatfield. Thanks!
