### ISSUE TITLE
Endless recursion when writing to a XCGFileLogDestination fails

### ISSUE THREAD

**Issue by suzukieng** [DaveWoodCom/XCGLogger#176]
Swift 2.3 / XCLogger 3.6 / macOS 10.10.5

Our application is crashing (non-deterministically), and from the crash log it seems like XCGLogger ends up in an infinite recursion, see attached crash log. I had a cursory glance at the implementation of XCGFileLogDestination and found something that I think might point into the right direction: if writing the log data in the output method of the XCGFileLogDestination fails, the NSException is caught, and logged... which is probably a bad idea, as it might end up failing again, and again, and again, ...

Excerpt:
`
public override func output(logDetails: XCGLogDetails, text: String) {

        let outputClosure = {
            if let encodedData = "\(text)\n".dataUsingEncoding(NSUTF8StringEncoding) {
                _try({
                    self.logFileHandle?.writeData(encodedData)
                },
                catch: { (exception: NSException) in
                    // DANGEROUS CODE HERE??
                    self.owner._logln("Objective-C Exception occurred: \(exception)", logLevel: .Error)
                })
            }
        }

        if let logQueue = logQueue {
            dispatch_async(logQueue, outputClosure)
        }
        else {
            outputClosure()
        }
    }`

Crash log:
[xcglogger-infinite-recursion.txt](https://github.com/DaveWoodCom/XCGLogger/files/613601/xcglogger-infinite-recursion.txt)

**Comment by DaveWoodCom** [comment]
Thanks for this. Good catch. Fixed in the next release (looks like tomorrow).
