### ISSUE TITLE
Crashes when running on xcode emulator

### ISSUE THREAD

**Issue by fmatosic** [DaveWoodCom/XCGLogger#178]
Version 8.2.1 (8C1002)
Using XCGLogger (4.0.0) by cocoa pods
crashes in app delegate:
log.setup(level: .debug, showThreadName: true, showLevel: true, showFileNames: true, showLineNumbers: true, writeToFile: nil, fileLevel: .none)
if run with emulator, if on real device it runs OK.
<img width="887" alt="screen shot 2017-01-06 at 21 25 05" src="https://cloud.githubusercontent.com/assets/3234580/21731833/a798e7a6-d456-11e6-9b98-5ffe1a577c7c.png">

**Comment by DaveWoodCom** [comment]
Unable to reproduce. Project specific issue?
