### ISSUE TITLE
XCGLogger will not be code signed because its settings don't specify a development team

### ISSUE THREAD

**Issue by jomnius** [DaveWoodCom/XCGLogger#183]
Found this warning in one failed build log, not related to failed build. Just wanted to report in case you might be able to fix it.

Temporary work-around found from http://stackoverflow.com/q/39485577/113079

**Comment by DaveWoodCom** [comment]
This is a normal Xcode thing, you need to ensure your build process signs all frameworks that you include. There are a few different ways of handling this, but it's handled on your project, not the framework.
