### ISSUE TITLE
Use of unresolved identifier 'Dev' and Tag

### ISSUE THREAD

**Issue by Ged2323** [DaveWoodCom/XCGLogger#185]
I'm not sure why these aren't working as my project looks exactly like the demo.
I'm going to try a manual import as the demo project doesn't use cocoa pods.

**Comment by ratzinho87** [comment]
The Dev and Tag classes are not included in the main XCGLogger pod. Try adding the `pod 'XCGLogger/UserInfoHelpers'` line to your podfile.
