### ISSUE TITLE
Setup XCGLogger fails on iOS 10.3 emulator

### ISSUE THREAD

**Issue by sohayb** [DaveWoodCom/XCGLogger#193]
Hello,
I'm trying to initialize the logger with the below code:
```swift
let logPath: URL = appDelegate.cacheDirectory.appendingPathComponent("XCGLogger_Log.txt")
log.setup(level: .verbose, showThreadName: true, showLevel: true, showFileNames: true, showLineNumbers: true, writeToFile: logPath)
```
The app gets stuck on `log.setup` instruction. This is not the case when passing `writeToFile` as `nil`. I was wondering if that has anything to do with the new Apple File System `APFS` pushed in iOS 10.3.

**Comment by idoNaveh** [comment]
I have the same problem with iPhone 7 and iOS 10.3. I can see that on 'setup' call memory increase until the app crash.

![screen shot 2017-04-03 at 14 37 35](https://cloud.githubusercontent.com/assets/10449688/24607665/8f803cd2-187b-11e7-9f68-ad11b48c6bdf.png)

**Comment by DaveWoodCom** [comment]
@idoNaveh Can you attach your set up code please? The path/filename you're using etc?

**Comment by idoNaveh** [comment]
This is my code for setup XCGLogger: 

```
public let dLog: XCGLogger? = {
    #if DEBUG
        let log = XCGLogger.default
        let date = String(Int64(NSDate().timeIntervalSince1970))
        let fileName = "log_\(date).txt"
        let logPath = documentsDirectory.appendingPathComponent(fileName)
        log.setup(level: .debug, showThreadName: true, showLevel: true, showFileNames: true, showLineNumbers: true, writeToFile: logPath)
        log.logAppDetails()
        return log
    #else
        return nil
    #endif
}()

let documentsDirectory: URL = {
    let urls = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
    return urls[urls.endIndex - 1]
}()
```

The call to log.setup(...) stuck and memory increase until the app crash

**Comment by racer1988** [comment]
I don't have the issue on 4.0.0
This seems to be related to 4.1.0 or 5.0.0 which are not official tags and slipped into the repo.

Try to run the same code on master level (4.0.0) and see if you have the same issue.

@DaveWoodCom will release soon a new version with the correct tags and that should also fix your issue

**Comment by DaveWoodCom** [comment]
Hopefully this explains why I haven't been able to reproduce the issue.

**Comment by sohayb** [comment]
Okay great! I will test this later today and close if if all works 👍

**Comment by einsteinx2** [comment]
I can confirm this appears to be fixed in the develop branch

**Comment by sohayb** [comment]
Yeap, it all work perfectly now! Thanks.

**Comment by einsteinx2** [comment]
Also appears fixed in master as well.
