### ISSUE TITLE
Question: master branch and 5.0.0

### ISSUE THREAD

**Issue by racer1988** [DaveWoodCom/XCGLogger#195]
Hello, simple question. 

Why master is on version 4.0.0 (Version_4.0.0) (swift_3.0)
while carthage and pod are receiving the new version 5.0.0?

This way, also develop does not contain the code of 4.1.0 and 5.0.0 but it is branched off master on 4.0.0

Is this a release design choice? (would be interesting to know for understanding how the project is maintained and learning something new :D) 

Would it be useful to merge this back to master and develop and update the readme? 

----
Also is 5.0.0 seems to be backward compatible to 4.0.0
There is any particular info/migration needed for it?

**Comment by racer1988** [comment]
I actually get the following error after building 5.0.0 with Carthage

@rpath/ObjcExceptionBridging.framework/ObjcExceptionBridging
  Referenced from: /Users/x/Library/Developer/CoreSimulator/Devices/XXX/data/Containers/Bundle/Application/XXX/x.app/Frameworks/XCGLogger.framework/XCGLogger
  Reason: image not found

**Comment by DaveWoodCom** [comment]
Hmm. Someone else added tags 4.1.0 and 5.0.0 to their branch, and when I merged in their commit (to my develop branch), it included those tags. I deleted them (I thought), but it looks like they're back.

Deleting them again. 4.1.0 should be out today (just wrapping up some new features).

**Comment by DaveWoodCom** [comment]
Ok, those tags appear to be deleted again. But now I wonder if I need to bump the real version up over 5.0.0 just to ensure everyone gets the real newest version.

**Comment by racer1988** [comment]
@DaveWoodCom Ok Cool! that makes sense 👍 

I checkout a fresh repo now and Wade Tregaskis tags and commits are gone (apart commit 969a4b9 which was integrated and is on develop)

There is a problem tough.
On my fork, the tags are still there, since the fork is not pruned from tags from upstream.
This means that all people that got these tags in their fork in the last months, could potentially bring them back (I don't think so, as you will not integrate their merges) or have duplicated tags (which is not even possible!?)

So there might be the need to keep this under control from time to time, or jump directly to a higher tag to avoid collisions altogether? (5.0.1 ?)

for history record I will paste here the incriminated commits and tags:

```
* bbae467 - (tag: 5.0.0) Added the ability to create overlays for loggers, where overlays provide the ability to set user info at creation time, rather than having to provide it at every single logging call site. (4 months ago) <Wade Tregaskis>
* 0876265 - Fixed an off-by-four error in the argument flag parsing. (4 months ago) <Wade Tregaskis>
* 39bd1ec - Whoops, forgot to push unrecognised arguments into the returned array. (4 months ago) <Wade Tregaskis>
* 6ea1caa - Always skip the first argument as it's the command the user executed, not parameters. (4 months ago) <Wade Tregaskis>
* b582312 - Added setup(fromCommandLineArguments:). (4 months ago) <Wade Tregaskis>
* a3eca08 - Corrected the buildable name for the ObjcExceptionBridging framework in the tvOS scheme (4 months ago) <Wade Tregaskis>
* 49f0bfb - (tag: 4.1.0) Fixed up the existing Xcode project file. (4 months ago) <Wade Tregaskis>
* 6e144be - Removed the duplicate XCGLogger.h. (4 months ago) <Wade Tregaskis>
* 42c4ec9 - Moved the Objective-C code (XCGLogger.h) into a separate module so that the Swift Package Manager can handle it correctly. (4 months ago) <Wade Tregaskis>
* 3b79433 - Moved the tests to the top-level "Tests" folder per Swift Package Manager expectations. (4 months ago) <Wade Tregaskis>
* de98ca5 - Added import statements for dependent modules (i.e. Dispatch & Foundation). (4 months ago) <Wade Tregaskis>
* f29c6dd - Added Swift '.build' folder to .gitignore. (4 months ago) <Wade Tregaskis>

```

**Comment by racer1988** [comment]
AHAH just saw your comment :D

Yes, I would suggest as a safe bet to bump to 5.0.1 to avoid any collisions.

**Comment by DaveWoodCom** [comment]
Thanks. Agreed. That sucks. lol.

**Comment by DaveWoodCom** [comment]
Done. 5.0.1 is out. Thanks for your help catching this issue. I'll have to be extra careful with merges in the future.
