### ISSUE TITLE
[Question] What time zone is used when dates are enabled, and can it be changed?

### ISSUE THREAD

**Issue by einsteinx2** [DaveWoodCom/XCGLogger#198]
I sometimes need to cross reference server side logs with client side logs by date. Is the local machine time zone used for logging, or is it in UTC/GMT? Also is there a way to choose the time zone for logging.

I took a quick look in the code, and I _think_ it's using local time zone, but I'm unsure. If so, I suppose I can just log the local time zone on launch. Otherwise, it would be nice to be able to select UTC/GMT so all logs use the same time zone for easy referencing.

**Comment by DaveWoodCom** [comment]
Yes, take a look here:

https://github.com/DaveWoodCom/XCGLogger/blob/master/Sources/XCGLogger/XCGLogger.swift#L138

By default, the logger uses a DateFormatter that uses local time. But you can create your own DateFormatter and set the logger to use that. Something like:

    log.dateFormatter = {
        let customDateFormatter = DateFormatter()
        customDateFormatter.locale = Locale(identifier: "en_CA")
        customDateFormatter.timeZone = TimeZone(abbreviation: "GMT")
        customDateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss.SSS"
        return customDateFormatter
    }()

**Comment by einsteinx2** [comment]
Awesome thanks!
