### ISSUE TITLE
Issues with targetMaxTimeInterval

### ISSUE THREAD

**Issue by vronin** [DaveWoodCom/XCGLogger#201]
There are two problems with targetMaxTimeInterval

1) The comments says "Option: desired maximum time in seconds stored in a log file, if 0, no maximum (log files may exceed this, it's a guideline only)"

However, the code does:

```
   if targetMaxTimeInterval < 1 {
                targetMaxTimeInterval = 600
            }
```

So, setting it to 0 will set it to 600 (vs infinity)

2) AutoRotatingFileDestination.init has code

```
   if shouldRotate() {
            rotateFile()
        }
```

This code is executed _before_ we had opportunity to set targetMaxTimeInterval or targetMaxFileSize. As result, this code will always check against default value (which is 600). So it will always rotate after an app restarted in 10 minutes.

**Comment by Gucky** [comment]
Found this issue, too.
Tackled it with a pull request  #-> #207

**Comment by DaveWoodCom** [comment]
#207 merged, should resolve this issue. Thanks!
