### ISSUE TITLE
Infinite recursion in AutoRotatingFileDestination / It doesn't work

### ISSUE THREAD

**Issue by laposheureux** [DaveWoodCom/XCGLogger#208]
1. The superclass initializes (`FileDestination`)
2. The superclass logs the file append divider
3. The superclass then logs app details
4. which calls write in the subclass (`AutoRotatingFileDestination`)
5. which in the `AutoRotatingFileDescription` checks to see if it should rotate the logs
  a. which it always will because this all happens before `currentLogStartTimeInterval` is set
  b. this means `currentLogStartTimeInterval` is zero so current time - 0 is never < 600
  c. so it rotates the logs
6. It tries to move the current log file to `defaultLogFolderURL` because `archiveFolderURL` can't possibly have been set yet because the superclass is still initializing
7. This fails because the folder does not yet exist

```
Error Domain=NSCocoaErrorDomain Code=4 "“currentSession.log.txt” couldn’t be moved to “log” because either the former doesn't exist, or the folder containing the latter doesn't exist." UserInfo={NSSourceFilePathErrorKey=/Users/aaron/Library/Developer/CoreSimulator/Devices/ED64DF21-6572-4EF2-8E9F-59375EE959E4/data/Containers/Data/Application/12784CBA-E624-42E4-8B14-03DE136FC4AE/Library/Caches/Logs/currentSession.log.txt, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/aaron/Library/Developer/CoreSimulator/Devices/ED64DF21-6572-4EF2-8E9F-59375EE959E4/data/Containers/Data/Application/12784CBA-E624-42E4-8B14-03DE136FC4AE/Library/Caches/log/xcglogger_2017-05-10_014512.log, NSFilePath=/Users/aaron/Library/Developer/CoreSimulator/Devices/ED64DF21-6572-4EF2-8E9F-59375EE959E4/data/Containers/Data/Application/12784CBA-E624-42E4-8B14-03DE136FC4AE/Library/Caches/Logs/currentSession.log.txt, NSUnderlyingError=0x610000057e20 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```
8. Which calls `openFile`
9. Goto 2.

The code logs the file separator and the app details about as many times as it takes for the stack trace to get 1000+ calls deep, and then the application crashes with EXC_BAD_ACCESS.

-----

I've setup a logger that for all intents and purposes is this (I also have a separate ConsoleDestination that works perfectly fine when this is not present):

```
let log = XCGLogger(identifier: "logger", includeDefaultDestinations: false)
let destination = AutoRotatingFileDestination(owner: log, writeToFile: logPath, identifier: "logger.rotatingFileDestination", shouldAppend: true, appendMarker: "❗️📝 New log 📝❗️", maxFileSize: 2097152, archiveSuffixDateFormatter: nil)
destination.targetMaxLogFiles = 5
destination.targetMaxFileSize = 2097152
destination.targetMaxTimeInterval = Double.greatestFiniteMagnitude
destination.outputLevel = .verbose
log.add(destination: destination)
```

Because of bugs mentioned in https://github.com/DaveWoodCom/XCGLogger/pull/207 I've set a very ridiculous interval time because I don't want time interval constrained logs and because the constructors maxFileSize is ignored I've set that as well.

`logPath` is computed elsewhere and resolves to "...Caches/Logs/currentSession.log.txt" and I've confirmed that at length with the debugger (and verified its existence and its contents in the filesystem both in simulator and on device) and even loaded it into an email and mailed it to myself. It's definitely there.

**Comment by laposheureux** [comment]
Maybe I'm doing something cataclysmically wrong, so if I've overlooked something obvious please let me know, but I don't see how `AutoRotatingFileDestination` works in its current incarnation.

**Comment by DaveWoodCom** [comment]
I believe this is now fixed with your merged PR. Please reopen if it's still an issue. Thanks.
