### ISSUE TITLE
Compatible with xCode 9 beta3?

### ISSUE THREAD

**Issue by hixfield** [DaveWoodCom/XCGLogger#217]
Doe snot compile with xCode 9/beta 3 I get the following error:

Undefined symbols for architecture arm64:
  "__T09XCGLoggerAAC4infoyypSgyXK_s12StaticStringV12functionNameAF04fileF0Si10lineNumbers10DictionaryVySSypG8userInfotFfA3_", referenced from: ..."

Anybody else having this issue?

**Comment by Maxim-Filimonov** [comment]
More errors here. Looks like swift 4 breaks it.
Pods/XCGLogger/Sources/XCGLogger/Extensions/URL+XCGAdditions.swift:17:36: Generic parameter 'ResultType' could not be inferred
Pods/XCGLogger/Sources/XCGLogger/Extensions/URL+XCGAdditions.swift:56:64: Cannot convert value of type '((UnsafePointer<Int8>?)) throws -> [String]' to expected argument type '(UnsafePointer<Int8>?) throws -> _'
Pods/XCGLogger/Sources/XCGLogger/Destinations/AutoRotatingFileDestination.swift:113:28: Subscripts returning String were obsoleted in Swift 4; explicitly construct a String from subscripted result
Pods/XCGLogger/Sources/XCGLogger/Destinations/AutoRotatingFileDestination.swift:120:45: Subscripts returning String were obsoleted in Swift 4; explicitly construct a String from subscripted result

**Comment by rubenhak** [comment]
I'm also hitting this issue. 

AutoRotatingFileDestination.swift:113
`baseFileName = baseFileName[baseFileName.startIndex ..< fileExtensionRange.lowerBound]`
should be changed to:
`baseFileName = String(baseFileName[baseFileName.startIndex ..< fileExtensionRange.lowerBound])`

and 

AutoRotatingFileDestination.swift:120
`let archiveFolderPath: String = filePath[filePath.startIndex ..< logFileNameRange.lowerBound]`
should be changed to:
`let archiveFolderPath: String = filePath[filePath.startIndex ..< logFileNameRange.lowerBound]`

**Comment by rubenhak** [comment]
Created a pull request with a fix: [https://github.com/DaveWoodCom/XCGLogger/pull/227](url)

**Comment by Maxim-Filimonov** [comment]
@rubenhak 404

**Comment by rubenhak** [comment]
Sorry, please try again the link above.

**Comment by matti777** [comment]
Hi, I am getting the following also using XCGLogger 5.0.1:
```

/Users/matti/src/qvik-network-ios/Pods/XCGLogger/Sources/XCGLogger/Destinations/AutoRotatingFileDestination.swift:113:28: error: subscripts returning String were obsoleted in Swift 4; explicitly construct a String from subscripted result
            baseFileName = baseFileName[baseFileName.startIndex ..< fileExtensionRange.lowerBound]
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                           String(                                                                )
/Users/matti/src/qvik-network-ios/Pods/XCGLogger/Sources/XCGLogger/Destinations/AutoRotatingFileDestination.swift:120:45: error: subscripts returning String were obsoleted in Swift 4; explicitly construct a String from subscripted result
            let archiveFolderPath: String = filePath[filePath.startIndex ..< logFileNameRange.lowerBound]
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                            String(                                                      )

```

Is there a version of XCGLogger current available via Cocoapods that compiles with Swift4?

**Comment by DaveWoodCom** [comment]
Will be released today.

**Comment by DaveWoodCom** [comment]
6.0.0 is the new version for Swift 4. Please let me know if you see any issues. If there are, we can get a point release done quickly to address them.

BTW, please (yes, I'm begging a bit), download my new app: [https://alltherings.fit/](https://alltherings.fit/?s=GH5) And tell your friends about it. I need to get the sales up, or get a real job. lol. Wife's patience is running out...
