### ISSUE TITLE
Question: Can the logger be instructed to capture ios error messages?

### ISSUE THREAD

**Issue by xyzisinus** [DaveWoodCom/XCGLogger#219]
The logger captures the developer's log messages.  However, the errors we see in the crash report, such as "nil pointer", are more indicative.  Is XCG logger designed for that but I just don't know how to use it?  Thanks!

**Comment by phimage** [comment]
Are you using swift only? When you talking about "nil pointer", did you use force cast or unwrap with `!`? (You must not use it except some exceptions)
It's a programming error. That cannot be caught.

**Comment by xyzisinus** [comment]
Thanks for your comments.  You are right.  I gave a poor example.  There are other error messages I'd like to capture into the log file, such as

[MC] System group container for systemgroup.com.apple.configurationprofiles path is ...

**Comment by DaveWoodCom** [comment]
Unfortunately not. Those are logs added by Apple and (as far as I know) there's no way to intercept them.
