### ISSUE TITLE
only show unicode characters with Chinese

### ISSUE THREAD

**Issue by ruixingchen** [DaveWoodCom/XCGLogger#221]
output is correct with system print , but only unicode characters with XCGLogger.
:p

**Comment by phimage** [comment]
could you provide an example?
Have you issues with all LogDestination? or a specific one like FileDestination

**Comment by DaveWoodCom** [comment]
@ruixingchen Can you please give me more info? A sample of the code you're using, the output you're seeing, and what you expect the output to be?
