### ISSUE TITLE
Infinite loop when there is no free space on the hard drive

### ISSUE THREAD

**Issue by davidmokos** [DaveWoodCom/XCGLogger#224]
The infinite loop happens in the `FileDestination` class when the mac is running out of disk space and the logger tries to write to a file. It fails because there is no free space and `self.owner?._logln()` is called, which tries to log to the file and it fails again, thus leading to an infinite execution loop.

The problematic code in the `FileDestination.swift` is as follows:

```swift            
_try({
    self.logFileHandle?.write(encodedData)
}, catch: { (exception: NSException) in
    self.owner?._logln("Objective-C Exception occurred: \(exception)", level: .error, source: self)
})
```

One possible solution would be to manage differently exceptions raised due to lack of disk space. For instance, we could introduce a new state variable in the FileDestination e.g `available: Bool`, that will indicate to the `owner` whether the destination can be used for logging, and when an exception is raised due to lack of space we could set the flag to `false`. Then, inside the implementation of `_logln` we could only ask available destinations to `processInternal(logDetails:)`

Alternatively we could override the `func process(logDetails: LogDetails)` function of the `FileDestination` and check whether there is available disk-space before relaying the call to super.

> Related Issues: #216

**Comment by DaveWoodCom** [comment]
This is fixed in 5.0.4.
