### ISSUE TITLE
XCGlogger output truncated when app crashes right after

### ISSUE THREAD

**Issue by procmail** [DaveWoodCom/XCGLogger#23]
Hi,

Just before a point where the app will crash, I have a log.verbose() line, which gets truncated:
2014-11-21 09:19:58.095 [Verbose] [MyViewController.swift:121] listDataCallback(_:response(lldb) 

To compare, I added a println() and that gets printed out fine.

**Comment by DaveWoodCom** [comment]
I've now added a `XCGNSLogDestination` log destination class that uses NSLog and is thus thread safe (though not as customizable). You should now use that class in cases where you're chasing a crash like that. This won't be an issue in Swift 2.0, since print() now appears to be thread safe.
