### ISSUE TITLE
Conversion Error in FileDestination.swift for Version 6.0.0 

### ISSUE THREAD

**Issue by TannerJuby1** [DaveWoodCom/XCGLogger#233]
After updating my pod file I am getting this error: 

    Cannot convert value of type '[FileAttributeKey : Any]?' to expected argument type '[String: Any]?'
    FileDestination.swift: 95

And this is the line: 

        if !shouldAppend || !fileExists {
            -> fileManager.createFile(atPath: writeToFileURL.path, contents: nil, attributes: fileAttributes)
        }

**Comment by DaveWoodCom** [comment]
Looks like you're using the Swift 4 version of XCGLogger (6.0.0) in Swift 3.x. Use 5.0.5 until you migrate to Swift 4.

**Comment by TannerJuby1** [comment]
Nope. I've upgraded to Swift 4 before I updated XCLogger. And just to make sure I double checked and I'm on Swift 4. You shouldn't close issues when they aren't closed.

**Comment by DaveWoodCom** [comment]
I closed it because it's a duplicate of the already closed issue #232.

The error you're seeing is only possible on Swift 3.x. Double check each target is set correctly. If you're using CocoaPods, check the Pods project, each target can have the Swift version set. You can mix and match btw.

**Comment by sunny635533** [comment]
How to set XCGLogger is  5.0.5  when in Swift 3.0? @DaveWoodCom ,could tell me? thanks!

**Comment by DaveWoodCom** [comment]
@sunny635533 That depends on how you're using XCGLogger. If you're using CocoaPods, just set the version in the pod `pod 'XCGLogger', '~> 5.0.5'`. If you're using a submodule, set the head of the checkout to the the 5.0.5 tag.

**Comment by sunny635533** [comment]
@DaveWoodCom thanks very much！It did work！
