### ISSUE TITLE
DebugMan -  iOS debugger tool for Swift

### ISSUE THREAD

**Issue by liman123** [DaveWoodCom/XCGLogger#241]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan) - iOS debugger tool for Swift
Welcome to use! 😃 thanks!
@st3fan @msanders @depl0y @kylebrowning @dearprakash

**Comment by DaveWoodCom** [comment]
@liman123 Please don't spam projects with fake issues. Thanks.
