### ISSUE TITLE
AutoRotatingFileDestination doesn't properly handle `maxFileSize` of 0 during initialization

### ISSUE THREAD

**Issue by laposheureux** [DaveWoodCom/XCGLogger#242]
Because `AutoRotatingFileDestination` accepts `maxFileSize` as a param during init and sets the `targetMaxFileSize` property immediately (during init), the `didSet` does not run, resulting in a `targetMaxFileSize` actually of 0 when sending 0 during init.

The effect of this is that the logs rotate almost immediately after the current file target receives some output.

Explicitly setting `targetMaxFileSize` after init to `.max` results in log files that receive more than about a half second of logs.

**Comment by DaveWoodCom** [comment]
Thanks. Should be fixed now.
