### ISSUE TITLE
AppStore rejection

### ISSUE THREAD

**Issue by TomaszWlodarczyk** [DaveWoodCom/XCGLogger#246]
I used to use XCLogger for a year now. Unfortunately for some reason after submitting my app last week to the TestFlight it was rejected. The reason was **Invalid binary**. After a week investigating I found that **ObjcExceptionBridging.framework** causes that issue and I needed to get rid of the whole library.  

Just letting you know. Maybe you'll be able to get to know more information from Apple.

**Comment by DaveWoodCom** [comment]
Hi @TomaszWlodarczyk, can you please check #245. This appears to be an iTunes Connect issue and is not related to XCGLogger.

Also check here: https://stackoverflow.com/q/48478143/144857 for some possible workarounds.

**Comment by TomaszWlodarczyk** [comment]
Yeah I tried everything what was described on stackoverflow. Nothing helped. 

Btw I am not using cocoapods but carthage. Maybe there is a reason?

**Comment by DaveWoodCom** [comment]
Shouldn't make a difference whether you are using CocoaPods or Carthage. They've changed something on the backend of iTC that's causing the issue. It's not an issue with XCGLogger though. I submitted a build on Sunday and had it approved today without issue. I suspect (but don't really know), it has to do with enabling/disabling bitcode. If you have bitcode disabled, try enabling it.
