### ISSUE TITLE
Dsymutil Warnings while using FileDestination

### ISSUE THREAD

**Issue by lug4rd** [DaveWoodCom/XCGLogger#248]
``
While processing ~/Library/Developer/Xcode/DerivedData/.../Build/Intermediates.noindex/Pods.build/Development-iphoneos/XCGLogger.build/Objects-normal/armv7/FileDestination.o:
warning: ~/Library/Developer/Xcode/DerivedData/ModuleCache/IX5UC9LT1DE6/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
note: The clang module cache may have expired since this object file was built. Rebuilding the object file will rebuild the module cache.
While processing ~/Library/Developer/Xcode/DerivedData/.../Build/Intermediates.noindex/Pods.build/Development-iphoneos/XCGLogger.build/Objects-normal/armv7/FileDestination.o:
warning: ~/Library/Developer/Xcode/DerivedData/ModuleCache/IX5UC9LT1DE6/ObjcExceptionBridging-RR9ASZ1Z1IRW.pcm: No such file or directory
``

**Comment by DaveWoodCom** [comment]
Hi. This doesn't appear to be an XCGLogger specific issue. Rather, just Xcode being Xcode. Wipe your DerivedData folder (I'd recommend running my [Watchdog for Xcode](https://itunes.apple.com/app/watchdog-for-xcode/id734258109?at=11lMGu&ct=GH&pt=17255&mt=12) app which will do this for you automatically). Then rebuild your app.
