### ISSUE TITLE
Unable to compile XCGLogger with XCode 9.3/Swift 4.1

### ISSUE THREAD

**Issue by rlubke** [DaveWoodCom/XCGLogger#251]
The following errors are produced:

> /Sources/XCGLogger/LogFormatters/XcodeColorsLogFormatter.swift:82:68: error: type 'NSColorSpaceName' (aka 'NSString') has no member 'calibratedRGB'
>             if let colorSpaceCorrected = color.usingColorSpaceName(NSColorSpaceName.calibratedRGB) {

> /Sources/XCGLogger/Destinations/FileDestination.swift:95:92: error: cannot convert value of type '[FileAttributeKey : Any]?' to expected argument type '[String : Any]?'
>             fileManager.createFile(atPath: writeToFileURL.path, contents: nil, attributes: fileAttributes)

**Comment by rustymyers** [comment]
I resolved my issue, which was self-caused by using a self-compiled framework. I've resolved my issue here. Thanks

**Comment by srinathz** [comment]
> **Cannot convert value of type '[FileAttributeKey : Any]?' to expected argument type '[String : Any]?'**

Still exist in Xcode Version 9.4.1 (9F2000)
XCGLogger (6.0.4)
