### ISSUE TITLE
iOS app crashes when Xcode instruments is used 

### ISSUE THREAD

**Issue by ehmjaysee** [DaveWoodCom/XCGLogger#253]
My app started crashing when I added XCGLogger.  I replicated the crash problem with a fresh new iOS app.  Just create a new Xcode project, install XCGLogger using cocoa pods, add some code to AppDelegate to initialize the log, select Product-->Profile, select Leaks, and the Instruments tool will start up.  Hit the record button to start the app and it will crash immediately.  Look at the crash log file and you should see something like this:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.cocoapods.XCGLogger       	0x00000001072d36dc XCGLogger.add(destination:) + 364 (XCGLogger.swift:1124)

```

My environment: 
Xcode 9.3
Swift 4.1
iOS 11.3

Code I added to AppDelegate:

```
import XCGLogger
let log = XCGLogger.default

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

var window: UIWindow?

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
log.setup(level: .debug, showLogIdentifier: true, showFunctionName: true, showThreadName: false, showLevel: true, showFileNames: true, showLineNumbers: true, showDate: false, writeToFile: nil, fileLevel: nil)
        return true
}
```

**Comment by NeverwinterMoon** [comment]
Can confirm that this is crashing my Instruments as well. When using the default config (all defaults but level set to .debug) and with advanced config, too. Xcode 9.3 and 9.4 with Swift 4.1 and XCGLogger 6.0.2. iOS 11.3 and 11.4. Emulator and real device alike.

**Comment by stardustWK** [comment]
It  seem like a Xcode 9.3 bug

**Comment by Prashant-Sah** [comment]
Instruments -> File -> Recording Options -> disabling record reference counts does not crash the app

**Comment by DaveWoodCom** [comment]
This does appear to have been a bug in Xcode 9.3. Able to reproduce in 9.3, but not 9.4 or 10 beta 1.

**Comment by ehmjaysee** [comment]
Thanks for chasing this down. It never occurred to me this might be a problem with Xcode itself. Now I know better.
