### ISSUE TITLE
beter lazy dateFormatter instantiation

### ISSUE THREAD

**Issue by hixfield** [DaveWoodCom/XCGLogger#255]
for instantiating the date formatter you could use the lazy closure way (instead of using the _ var duplicate).

    private static var dateFormatter: DateFormatter = {
                    let defaultDateFormatter = DateFormatter()
                    defaultDateFormatter.locale = NSLocale.current
                    defaultDateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss.SSS"
                    return defaultDateFormatter
    }()

It more the swift-way :)

**Comment by DaveWoodCom** [comment]
We're already doing this lazily. The reason we use the 'duplicate' private variable is so that someone can set their own custom DateFormatter and avoid us creating one that won't be used.
