### ISSUE TITLE
flatMap Deprecation and Overlapping accesses issues

### ISSUE THREAD

**Issue by MMooreGitHub** [DaveWoodCom/XCGLogger#256]
Class: 
XCGLogger -> Core -> URL+XCGAdditions.swift

Issues:
1. I'm receiving the following warning using Pod version 6.0.2
'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value
2. 'Overlapping accesses to 'data', but modification requires exclusive access; consider copying to a local variable' Lines 26 & 70

**Comment by ijaureguialzo** [comment]
There's already a patch for it, but the updated pod is not released yet.

Meanwhile, you can change your Podfile and use the master branch:

`pod 'XCGLogger', :git => 'https://github.com/DaveWoodCom/XCGLogger.git'`

Then do a `pod install` and the warnings should be gone.

**Comment by MMooreGitHub** [comment]
Ok, thank you @ijaureguialzo. I appreciate the advice and look forward to the update.

**Comment by neilt** [comment]
The overlapping access is now a failure with the new Xcode beta released today.  Any chance of getting a release?

**Comment by DaveWoodCom** [comment]
Yes. Working on it.

**Comment by neilt** [comment]
Excellent, thank you.

**Comment by DaveWoodCom** [comment]
6.0.4 is now available as a pod etc. Fixes these issues (and a few more).
