### ISSUE TITLE
Overlapping accesses to 'data' (Xcode 10 beta, Swift 4.2)

### ISSUE THREAD

**Issue by Zyphrax** [DaveWoodCom/XCGLogger#259]
In Xcode 10 beta with Swift 4.2 there are two build errors, in [URL+XCGAdditions.swift](https://github.com/DaveWoodCom/XCGLogger/blob/master/Sources/XCGLogger/Extensions/URL%2BXCGAdditions.swift) (line 26 and 64):
> Overlapping accesses to 'data', but modification requires exclusive access; consider copying to a local variable

![image](https://user-images.githubusercontent.com/966500/41114899-c4be5e6c-6a53-11e8-9474-a3ce2dc4458c.png)

I think the issue is that you are referring to `data` inside of the `withUnsafeMutableBytes` block. The block is reading the `data` variable (with `data.count`) while it is modifying the `data` variable.

A potential fix would be to replace `data` with `$0.pointee`, but I'm not sure if that is just hiding the problem. Perhaps it would be better to extract the `data.count` into a separate variable before you enter the block and use that inside the block.

**Comment by lifely** [comment]
This is actually already fixed on master.
There would need to be a release done w/ cocoapods in order to update dependencies easily ?

**Comment by bystritskiy** [comment]
We will wait for updates for cocoapods

**Comment by cikpis** [comment]
Actually the `data.count` can be replaced with `lenght` :)

**Comment by DaveWoodCom** [comment]
6.0.4 is now available as a pod etc. Fixes these issues (and a few more).

**Comment by sglushchenko** [comment]
I see it again. XCode 10, Swift 4

**Comment by mithun-grmtech** [comment]
I am getting the same error in Xcode 10.1
My pod version: 1.7.0.beta.3 
Anyone can sagest me
![Screenshot 2019-04-11 at 12 46 57 AM](https://user-images.githubusercontent.com/15921165/55939756-64554080-5bf3-11e9-8fc7-b2e623b61aae.png)

**Comment by DaveWoodCom** [comment]
Hi @mithun-grmtech, you are most likely using the wrong version of XCGLogger.
If you're using Xcode 10.1, you should be using version 6.1.0 of XCGLogger, so make sure you specify that in your Podfile:

```
pod 'XCGLogger', '~> 6.1.0'
```

If you're still having issues after this, please ask a question on StackOverflow, and include the contents of your Podfile.

**Comment by mithun-grmtech** [comment]
I am getting the same ERROR
My pod version is 1.7.0.beta.3

![Screenshot 2019-04-11 at 12 46 57 AM](https://user-images.githubusercontent.com/15921165/56018657-8adcaf80-5cb7-11e9-967e-32b3dd605b94.png)

**Comment by mithun-grmtech** [comment]
Hi @DaveWoodCom, Thank you
Now it's working fine.
👍
