### ISSUE TITLE
Crash when initializing XCGlogger

### ISSUE THREAD

**Issue by nick3389** [DaveWoodCom/XCGLogger#263]
Hi,
When I try to launch the app I have a crash. This is printed in the debugger:

`
dyld: lazy symbol binding failed: Symbol not found: __T09XCGLogger27AutoRotatingFileDestinationCAc2ACSg5owner_yp07writeToD0SS10identifierSb12shouldAppendSSSg12appendMarkers10DictionaryVySC0D12AttributeKeyVypGSg10attributess6UInt64V03maxD4SizeSd0S12TimeIntervalSo13DateFormatterCSg013archiveSuffixwX0s5UInt8V17targetMaxLogFilestcfc
`

Do you have any idea how to resolve this?

**Comment by phimage** [comment]
cocoapod? carthage? others method

try to clean, clean build folder and remove derived data

and then for instance you could have this with carthage if you do use copy-frameworks phase
