### ISSUE TITLE
AutoRotatingFileDestination clears the log even if shouldAppend is true

### ISSUE THREAD

**Issue by emovla** [DaveWoodCom/XCGLogger#264]
AutoRotatingFileDestination almost always clears(rotates) the log even if shouldAppend is true,
unless maxTimeInterval is specified when calling the initializer. (vs setting it a bit later)
In the check near the end of the initializer: 
```
        if !shouldAppend || shouldRotate() {
            rotateFile()
        }
```
shouldRotate() returns true because sees the default 600 second time interval.

**Comment by phimage** [comment]
configure `targetMaxTimeInterval` to 0 (the default is 600) if you do not want rotate on time internal

**Comment by DaveWoodCom** [comment]
When creating the `AutoRotatingFileDestination` object, set `maxTimeInterval` in the init. As @phimage mentions, set it to `0` if you want to keep all old logs regardless of age, or set another time that's more appropriate for your needs. Perhaps `86400` for a day etc.
