### ISSUE TITLE
Module compiled with Swift 4.0.2 cannot be imported in Swift 3.3: /Users/administrator/Documents/workspace/51xianqu/yhgj/Carthage/Build/iOS

### ISSUE THREAD

**Issue by puyangdev** [DaveWoodCom/XCGLogger#267]
Module compiled with Swift 4.0.2 cannot be imported in Swift 3.3: /Users/administrator/Documents/workspace/51xianqu/yhgj/Carthage/Build/iOS

**Comment by DaveWoodCom** [comment]
This appears to be a Carthage issue. I'd try asking on StackOverflow... Sorry.
