### ISSUE TITLE
ObjcExceptionBridging

### ISSUE THREAD

**Issue by hk05** [DaveWoodCom/XCGLogger#270]
Just installed macOS Mojave with xcode 10 (fresh install). When trying to rebuild my project, XCGLogger build fails with the following error:

Carthage/Checkouts/XCGLogger/Sources/XCGLogger/Misc/HelperFunctions.swift:11:8: error: no such module 'ObjcExceptionBridging'

Cartfile contains: 
github "DaveWoodCom/XCGLogger" ~> 6.1

How can this be resolved? Thanks!

**Comment by DaveWoodCom** [comment]
Did you follow the instructions here: https://github.com/DaveWoodCom/XCGLogger#carthage

I believe it specifically explains how to fix this issue with Cathage. (Though I don't use Cathage myself).

**Comment by hk05** [comment]
Hi Dave,

I did read the section you refer to and did follow it.

I did use  "carthage update --no-use-binaries". The last part of the instruction (add $(SRCROOT)/Carthage/Build/iOS/ObjcExceptionBridging.framework to the input files) seems not relevant at the Carthage update stage, as Carthage building does not (yet) require a project, it just creates the frameworks. 

You can try yourself:

1. create a cart file with github "DaveWoodCom/XCGLogger" ~> 6.1
2. $ carthage update --no-use-binaries

Carthage/Checkouts/XCGLogger/Sources/XCGLogger/Misc/HelperFunctions.swift:11:8: error: no such module 'ObjcExceptionBridging'

Apparently XCGLogger.framework depends on ObjcExceptionBridging.framework?

As far as I can see, closing the issue instantly is a bit premature...

Thanks.

**Comment by hk05** [comment]
Hi Dave, 

Would you please reopen this issue? I have been trying to fix this, but got completely stuck. 

You should be able to reproduce this issue.

1. fresh install xcode 10 (on macOS Mojave)
2. create a directory with cartfile
3. in Carttfile put one line "github "DaveWoodCom/XCGLogger" ~> 6.1"
4. run carthage update --nu-use-binaries --platform macOS

Yo should then see a build error:
Build Failed
	Task failed with exit code 65:
referring to a log that further shows the issue at stake:
...Checkouts/XCGLogger/Sources/XCGLogger/Misc/HelperFunctions.swift:11:8: error: no such module 'ObjcExceptionBridging'
import ObjcExceptionBridging

I did read your instructions on ObjCExceptionBridging, but how should one fix this in Carthage, i.e. Carthage is run from the command line, not from a xcode project. So it is very unclear to me how the ObjCException problem should be fixed, when only "carthage update" can be run?
