### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by TaylorNeoma** [DaveWoodCom/XCGLogger#275]
您好，在安装第三方库的时候出现权限错误

**Comment by phimage** [comment]
@TaylorNeoma please close

**Comment by DaveWoodCom** [comment]
Using Google Translate:

Q. Hello, there is a permission error when installing the third-party library.

A. You would need to give me some more information. I recommend using CocoaPods since it seems to be the easiest method.

您需要向我提供更多信息。 我建议使用CocoaPods，因为它似乎是最简单的方法。
