### ISSUE TITLE
打印数据太多的时候，打印不全

### ISSUE THREAD

**Issue by FunnyFzl** [DaveWoodCom/XCGLogger#281]
打印数据太多的时候，打印不全

**Comment by FunnyFzl** [comment]
log.debug（）的时候

**Comment by DaveWoodCom** [comment]
Using Google Translate:

Q. When printing too much data, printing is not complete.

A. This depends on the log destination you use. The system print() and NSLog() calls do have limits. This is outside the control of XCGLogger, sorry. You could use an alternate log destination.

这取决于您使用的日志目标。 系统print（）和NSLog（）调用确实有限制。 对不起，这不受XCGLogger的控制。 您可以使用备用日志目标。
