### ISSUE TITLE
Initializer for conditional binding must have Optional type, not 'Data'

### ISSUE THREAD

**Issue by ClegeJJ** [DaveWoodCom/XCGLogger#284]
XCGLogger (6.1.0)
Swift version: 5.0

![image](https://user-images.githubusercontent.com/13790283/55395341-eac6ae00-5573-11e9-8b51-2d453870484a.png)

**Comment by 3s-tiennm** [comment]
Same issue, @ClegeJJ Are you fixed it?

**Comment by DaveWoodCom** [comment]
@3s-tiennm Please make sure you're using the right version of XCGLogger for the version of Swift you're working with. The above issue was due to using XCGLogger 6.1.0 with Swift 5.0, instead of XCGLogger 7.0.

See https://github.com/DaveWoodCom/XCGLogger#backwards-compatibility
