### ISSUE TITLE
Would it makes sense to remove XCG prefix?

### ISSUE THREAD

**Issue by nikita-leonov** [DaveWoodCom/XCGLogger#29]
Code is written in swift, swift by default has proper name-spacing.  Would it makes sense to name it just Logger and keep XCG for branding purposes in README.md, but not in code?

**Comment by DaveWoodCom** [comment]
I'm waiting to see how namespaces shape up. It's also a concern that some people just drop the main .Swift file into their projects, rather than use a module. There are a few things I'll probably change for a 2.0 release, and this may be included in that.

**Comment by DaveWoodCom** [comment]
This has been done for the https://github.com/DaveWoodCom/XCGLogger/tree/swift_3.0 branch.
