### ISSUE TITLE
log level implementation incomplete?

### ISSUE THREAD

**Issue by hk05** [DaveWoodCom/XCGLogger#296]
The readme gives the impression that one can use the new log levels log.alert("something"), lag.notice("something") and log.severe("something") in a way similar to the other log levels (e.g. log.debug et al).

The methods from the readme/Basic Usage (Quick Start) cannot be used  (for example: "log.notice("A notice message")" results in a compiler error). In the source code I can see that the log levels have been implemented, but not the functions. 

I assume that the implementation is not complete yet? Or is it supposed to be used in a different way (in which case the readme is confusing).

**Comment by DaveWoodCom** [comment]
@hk05 You're correct. No idea how I missed that. Will update shortly. Thanks for pointing this out.

**Comment by DaveWoodCom** [comment]
Fixed in 7.0.1 Thanks again.
