### ISSUE TITLE
Attempt to open log file for writing failed: Optional("The operation couldn’t be completed. (Cocoa error 2.)")

### ISSUE THREAD

**Issue by nickvelloff** [DaveWoodCom/XCGLogger#31]
Hi. Thanks for the great library.
I get the following errors:
2015-01-14 23:44:11.316 [Info] : Share1 Version: 1.0 Build: 21 PID: 701
2015-01-14 23:44:11.316 [Info] : XCGLogger Version: 1.8.1 - LogLevel: Debug
2015-01-14 23:44:11.350 [Error] : Attempt to open log file for writing failed: Optional("The operation couldn’t be completed. (Cocoa error 2.)")

Version 6.1.1 (6A2008a)

Here is my config:
log.setup(logLevel: .Debug, showLogLevel: true, showFileNames: true, showLineNumbers: true, writeToFile: "logging/debug")

Does the file need to already exist? If so what is the root of the path in the project?

**Comment by DaveWoodCom** [comment]
The file does not need to exist, but you should specify a full path.  See here: https://github.com/DaveWoodCom/XCGLogger/blob/master/XCGLogger/DemoApps/iOS/iOSDemo/iOSDemo/AppDelegate.swift for an example.

The folder should exist already of course. So your "logging" folder needs to exist (again: best to include a full path), and then a file called "debug" will be created. I'd also recommend adding a file extension.

**Comment by oniksfly** [comment]
Use this [link for example](https://github.com/DaveWoodCom/XCGLogger/blob/master/DemoApps/iOSDemo/iOSDemo/AppDelegate.swift).
