### ISSUE TITLE
The end of the file log has "[m"

### ISSUE THREAD

**Issue by DeTong** [DaveWoodCom/XCGLogger#312]
XCode log is no problem.
This makes me very confused.
![image](https://user-images.githubusercontent.com/8585882/103402832-e421fc00-4b88-11eb-82ed-a66bd36e393c.png)

**Comment by Manfred-Wang** [comment]
The same problem! Logs always have additional sting "[m"

**Comment by DaveWoodCom** [comment]
Remove `XcodeColorsLogFormatter` from your set up. Xcode no longer supporters colours in the console area. The `XcodeColorsLogFormatter` is only useful now if you're logging to an external source compatible with ANSI codes.
