### ISSUE TITLE
Log output does not appear in system console, only debug console 

### ISSUE THREAD

**Issue by nickvelloff** [DaveWoodCom/XCGLogger#32]
![screenshot 2015-01-14 23 57 08](https://cloud.githubusercontent.com/assets/885369/5752707/274a18f0-9c49-11e4-901c-e6a7a4e6a863.png)

**Comment by DaveWoodCom** [comment]
By default, logs are sent to the debug console using the println() function. You can create additional log destinations following the sample in the library.

**Comment by nickvelloff** [comment]
Could you perhaps point me to the sample? Do you mean looking at the source code for XCGConsoleLogDestination?

**Comment by nickvelloff** [comment]
Is this it:

import Foundation
import XCGLogger
```swift
class ConsoleLogDestination: XCGConsoleLogDestination {
    
    internal override func processLogDetails(logDetails: XCGLogDetails) {
        // do my own here
    }
}
```
