### ISSUE TITLE
How Can I color with font

### ISSUE THREAD

**Issue by wfs498121294** [DaveWoodCom/XCGLogger#320]
Hello ,

I use  ANSIColorLogFormatter, but it not work 
        let ansiColorLogFormatter = ANSIColorLogFormatter()
        ansiColorLogFormatter.resetFormatting()
        log.formatters = [ansiColorLogFormatter]

so  I find   [ColoredConsole](https://github.com/jjrscott/ColoredConsole) can color logger , but  I do not  have idea work with XXGLogger . can you help me

I  use it as this 

 logger.debug("debug".debugColor())
 logger.info("info".infoColor())

I do not know  how to cofigure it

**Comment by DaveWoodCom** [comment]
Xcode no longer supports ANSI colour in the console so ANSIColorLogFormatter isn't useful there anymore. It can be used if you're outputting your logs to a file and then watching that file in a terminal that does support ANSI colours.

The [ColoredConsole](https://github.com/jjrscott/ColoredConsole) project uses a custom font to display colour. I don't see why you couldn't create a custom LogFormatter that then uses ColoredConsole to colourize the text.
