### ISSUE TITLE
XCGLogger with privacy manifest to support iOS 14.0

### ISSUE THREAD

**Issue by parvez-keeptruckin** [DaveWoodCom/XCGLogger#334]
`XCGLogger` with `v7.1.1` has now Privacy Manifest included in it. But it has also set minimum iOS Deployment target to `iOS 15`. We want to update `XCGLogger` version to 7.1.1 but getting restricted by minimum iOS Deployment target. What is the reason for updating the iOS deployment target ? 
@DaveWoodCom Can you provide us a version of XCGLogger that has both privacy manifest and iOS 14 support ? Otherwise it will require us to upgrade our iOS app's minimum iOS deployment target.

**Comment by DaveWoodCom** [comment]
XCGLogger 7.1.3 changes the deployment targets to the minimum allowed by Xcode 15.3. iOS = 12.0, watchOS = 4.0, tvOS = 12.0, macOS = 10.13. This should resolve your issue.

**Comment by parvez-keeptruckin** [comment]
@DaveWoodCom Thanks for the updates.
is `7.1.3` available on cocoapods? I do not see it there.

**Comment by DaveWoodCom** [comment]
@parvez-keeptruckin It is. But since it was just pushed, you likely have to update your local cache with `pod repo update`

**Comment by parvez-keeptruckin** [comment]
> @parvez-keeptruckin It is. But since it was just pushed, you likely have to update your local cache with `pod repo update`

@DaveWoodCom Actually I was the cocoapods website and there I did not see the version `7.1.3`.
<img width="1212" alt="Screenshot 2024-04-29 at 2 46 21 PM" src="https://github.com/DaveWoodCom/XCGLogger/assets/87128187/2f0383d6-e13c-49ba-99af-76a1f8e912dd">

**Comment by DaveWoodCom** [comment]
@parvez-keeptruckin Their search results are broken, has been for years. The version shown in the results list does not match what's actually there. Tap the entry and it shows 7.1.3.
