### ISSUE TITLE
Privacy manifest duplicate symbols

### ISSUE THREAD

**Issue by reeq-dev** [DaveWoodCom/XCGLogger#336]
Basically i faced error when i build pod as static framework, when privacy manifest which is coming from ObjcExceptionBridging make an install source as root which is conflicts with my own privacy manifest file and fires such error:

`Multiple commands produce '../Xcode/DerivedData/AppName-bebhynvudzxapxafdsamsgmmwrcb/Build/Products/Debug-iphonesimulator/AppName.app/PrivacyInfo.xcprivacy'`

After checking `Pods/Target Support Files/Pods-AppName/Pods-AppName-resources.sh` found such thing:

`install_resource "${PODS_ROOT}/ObjcExceptionBridging/Sources/ObjcExceptionBridging/PrivacyInfo.xcprivacy"`:
Which says that XCGLogger PrivacyInfo setting directly to the root which is conflicts with my own privacy manifest for specific target. The solution and description can be found here:

https://guides.cocoapods.org/syntax/podspec.html#resource_bundles
https://stackoverflow.com/questions/78247650/multiple-commands-produce-privacyinfo-xcprivacy

**Comment by DaveWoodCom** [comment]
Fixed in 7.1.5. Thanks for reporting this. Your links were really helpful. I wasn't able to reproduce the issue for a while until I noticed your note about using static libraries instead of dynamic.
