### ISSUE TITLE
iOS 7 compatibility

### ISSUE THREAD

**Issue by appsird** [DaveWoodCom/XCGLogger#34]
I recently started the process of validating my project in xcode for deployment inTunes connect. I currently receive a warning:

PBXCp Warning
warning: skipping copy phase strip, binary is code signed...

Regarding XLGLogger

Does the logger work with iOS7, which apparently iTunes connect requires currentlyfor distribution.

![untitled 2](https://cloud.githubusercontent.com/assets/8471833/5941374/7cad28a6-a6c5-11e4-8be8-7b0c99235b4c.png)

**Comment by appsird** [comment]
In the above, do I need to be concerned with this warning, or can I ignore?

**Comment by DaveWoodCom** [comment]
This is more of an Xcode issue. Please see here: https://groups.google.com/d/msg/growl-development/hEISmJIWXdc/lm62Z02-m1cJ

If you're still having this issue, please post a question on StackOverflow tagged with xcglogger:

http://stackoverflow.com/questions/tagged/xcglogger

Thanks.
