### ISSUE TITLE
Problem running on iPhone 5s with iOS 8.1.3

### ISSUE THREAD

**Issue by cwoloszynski** [DaveWoodCom/XCGLogger#35]
I am using XCGLogger while developing my app and it is great in the simulator.  However, I just tried to run it on my device.

I am building this using the framework as a sub-project, in my project Jeeves.  

Does this error make any sense?  It seems to be saying that dyld had issues loading the XCGLogger because of a missing image.  But I don't see any images in the entire framework.  Thoughts?

dyld: Library not loaded: @rpath/XCGLogger.framework/XCGLogger
  Referenced from: /private/var/mobile/Containers/Bundle/Application/E406EE87-EA20-4B3E-A280-A754572E91E6/Jeeves.app/Jeeves
  Reason: image not found

**Comment by PascalGiessler** [comment]
Add the XCGLogger.framework to the "Embedded Binaries" section and the error goes away ;) I assume  that you have added the framework to the linked frameworks and libraries section.

**Comment by cwoloszynski** [comment]
Thanks for the suggestion.  I tried it but I still get:

dyld: Library not loaded: @rpath/XCGLogger.framework/XCGLogger
  Referenced from: /private/var/mobile/Containers/Bundle/Application/A74A1A17-D606-4DF1-9700-3346C46D31EB/Jeeves.app/Jeeves
  Reason: image not found
(lldb)

**Comment by DaveWoodCom** [comment]
Pascal's answer should fix the issue for you. This is a Swift thing more than just this library.

See here: http://stackoverflow.com/a/24345546/144857

If you're still having this issue, please post a question on StackOverflow tagged with xcglogger:

http://stackoverflow.com/questions/tagged/xcglogger

Thanks.
