### ISSUE TITLE
Distribution as a CocoaPod

### ISSUE THREAD

**Issue by steilerDev** [DaveWoodCom/XCGLogger#37]
I am looking for a logging framework and your project looks like a great tool! Unfortunately you are currently not offering the framework as a CocoaPod, which is my dependency management application.

Are you planing on including your framework to the CocoaPod project soon?

**Comment by rromanchuk** [comment]
+1  This needs a spec.

**Comment by beltex** [comment]
See https://github.com/DaveWoodCom/XCGLogger/pull/18

**Comment by mwaterfall** [comment]
+1

**Comment by steilerDev** [comment]
Hey @DaveWoodCom, I have just seen your latest release note saying "Add experimental support for CocoaPods". How can I take advantage of this support?

**Comment by DaveWoodCom** [comment]
Done. Think it should work. I don't use CocoaPods myself, which is why I'm saying it's experimental.

Add `pod 'XCGLogger', '~> 2.0'` to your Podfile.

I've only added it to version 2.0, not 1.9 or below, so you'll need to update to Swift 1.2 if you haven't already done so. Let me know if there are any issues.

**Comment by steilerDev** [comment]
Just included it as pod. Looks very good! Thank you.

**Comment by mwaterfall** [comment]
Thanks @DaveWoodCom!

**Comment by zheref** [comment]
Not working for me with this Podfile:

    platform :ios, '8.0'
    pod "Parse"
    pod 'ParseFacebookUtils'
    pod 'Optimizely-iOS-SDK'
    pod 'Brightcove-Player-SDK'
    pod 'Bugsnag', :git => "https://github.com/bugsnag/bugsnag-cocoa.git"
    pod 'M13Checkbox', :git => "https://github.com/Marxon13/M13Checkbox.git"
    
    use_frameworks!
    
    pod 'XCGLogger'

This error appears when "pod install"
[!] The 'Pods' target has transitive dependencies that include static binaries: (A LONG PATH)

**Comment by DaveWoodCom** [comment]
@zheref A quick search says this is a CocoaPods issue: https://github.com/CocoaPods/CocoaPods/issues/3194

**Comment by zheref** [comment]
@DaveWoodCom Yes. But I've not found out how to solve it. I need the libraries from above as normal cocoapods libraries and XCGLogger as framework due to it's on Swift. I was requested to add "use_frameworks!" due to that. But then I got this error message.

This is the complete process log:

    Analyzing dependencies
    Downloading dependencies
    Using Bolts (1.1.4)
    Using Brightcove-Player-SDK (4.3.3)
    Using Bugsnag (4.0.4)
    Using Facebook-iOS-SDK (3.23.0)
    Using M13Checkbox (1.1.2)
    Using Optimizely-iOS-SDK (1.0.78)
    Using Parse (1.6.4)
    Using ParseFacebookUtils (1.6.4)
    Installing XCGLogger (2.0)
    [!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/zheref/Code/skillet/skillet-ios/Pods/Parse/Parse.framework)
    Failed with exit code: 1
