### ISSUE TITLE
Disable logging to console?

### ISSUE THREAD

**Issue by ProjectDent** [DaveWoodCom/XCGLogger#38]
My purpose for using this library was that everything could be logged to files that I could go back and check later. This includes info logs, as well as error logs. I wanted to be able to track the course of my app, and see why a certain behaviour might have happened, or want to make sure that things have consistently ran as expected, but at the same time I'm likely to be busy developing new things, and not want to  clutter up my console with info logs about these various parts of the app.

So my request is: I'd like to have the option to have everything logged to a file and not the console. Or perhaps console logs that start at a different level.

**Comment by DaveWoodCom** [comment]
Just an FYI, when I have a chance I'll add this option. Most likely for a version 2.0 (Swift 1.2).

**Comment by DaveWoodCom** [comment]
This was actually already possible in the library, but I've added an easier way to do it. There's now a `fileLogLevel` parameter of the `setup()` method that lets you set a different log level for the file. The read me has an example.
