### ISSUE TITLE
Swift 1.2 compatibility

### ISSUE THREAD

**Issue by va1da** [DaveWoodCom/XCGLogger#49]
Hi,
would like to use XCGLogger with Xcode 6.3 and Swift 1.2, but it won't compile.

Thanks,
O.

**Comment by DaveWoodCom** [comment]
There's a swift_1.2 branch you can use for now. I'm currently working on a 2.0 update that incorporates some of the PR's I've received and some new features that will be Swift 1.2 only. I hope to have that available this week. Time permitting.
