### ISSUE TITLE
How to add embedded framework?

### ISSUE THREAD

**Issue by fabnoe** [DaveWoodCom/XCGLogger#5]
Hi
i was wondering how to add the library as an embedded framework to a new project? 
The demo works fine, but I have no idea how to add the framework to my existing project.

thanks

**Comment by camgas** [comment]
For me things are working fine in AppDelegate but in a ViewController I am getting:

Cannot invoke 'info' with an argument list of type '(String)'

when trying to do something like:

log.info("Trying to login")

**Comment by peteclark3** [comment]
+1 to @camgas comment
