### ISSUE TITLE
Is there anyway to wrap the usage?

### ISSUE THREAD

**Issue by mabril** [DaveWoodCom/XCGLogger#50]
Hello, we find very useful this Logger but we want to wrap it on our own Logger class, for the case that in a future we want to do more things on Log events (send to our servers, change to another framework...)

But we do not want to lose the functionality of print the file, class and line of the current log message. 

¿any ideas?

Thanks

**Comment by DaveWoodCom** [comment]
You could create a custom XCGLogDestination (similar to this: https://gist.github.com/DaveWoodCom/71fbb90ca58fd058bf97 ) that sends the log messages to your server or whatever. The library is architected to be very flexible and should be easy enough to extend to your purposes.

As for wrapping it so you can move to another framework later, why would you ever leave? ;) Though that should be easy enough as well, just look at how the ```logln()``` method uses default values for ```__FUNCTION__```, ```__FILE__``` etc.
