### ISSUE TITLE
Read the log file while the app is running

### ISSUE THREAD

**Issue by mabril** [DaveWoodCom/XCGLogger#52]
We're doing a console for the app, and the idea is to print in a TextView the contents of the log file.

The writting is ok but when we try to read the file it fails because the file is not close.

Any workaround for this issue?

Thanks

**Comment by DaveWoodCom** [comment]
Yes, this is a good example of creating custom log destinations. I've just whipped up a quick one here:

https://gist.github.com/DaveWoodCom/71fbb90ca58fd058bf97

You can tweak it as needed, perhaps add new logs to the top instead of the bottom, or cycle so you have a max of 100 lines or something.
