### ISSUE TITLE
Is there a way to install from cocoapods and deployment target as iOS 7.0 or 7.1?

### ISSUE THREAD

**Issue by maykonmeier** [DaveWoodCom/XCGLogger#55]
To install from cocoapods I need to have deployment target setted as iOS 8.0 or greater.

Is there a way to be 7.0 or 7.1?

Thanks.

**Comment by harinsa** [comment]
I have the same issue.

**Comment by DaveWoodCom** [comment]
Sorry, iOS 7 doesn't handle frameworks very well and so it's not supported. If you really need iOS 7 support, you can drop the `XCGLogger.swift` file into your project directly and you're good to go.
