### ISSUE TITLE
Add the ability to remove all additional informations

### ISSUE THREAD

**Issue by Domsou** [DaveWoodCom/XCGLogger#59]
This is a need I have: only log messages but additional informations such as date, function name...

Thank to multiple instances feature, I create a file log for a very specific usage to trace the evolution of some data structure. This is for a game where I want to log each player move in order to have the game history. It then allow me to replay that game, first for development purposes then for future additional game features.

By logging only the wanted data I then can format a file I can use as-is: i.e.  in JSON or XML format or anything else.

**Comment by DaveWoodCom** [comment]
The latest update now lets you hide the date and function name, but if you want to write out JSON or XML, you may need to create your own subclass of the `XCGBaseLogDestination` class.
