### ISSUE TITLE
Rolling Frequency, File Size etc...

### ISSUE THREAD

**Issue by pavm035** [DaveWoodCom/XCGLogger#66]
Hi,

It's really great class for logging, but i feel like it would be nice if  we have option to set rolling frequency, file limit etc... like CocoaLumberjack..

**Comment by mastro35** [comment]
I agree, this would be great!

**Comment by mtzaquia** [comment]
+1

**Comment by memmaker650** [comment]
That's mandatory for include the library in a production app.
Like in CocoaLumberJack or Log4Java.

**Comment by serhattopkaya** [comment]
I agree, need for production

**Comment by ryanholden8** [comment]
+1

**Comment by xyzisinus** [comment]
Would love to have it.

**Comment by xyzisinus** [comment]
Just opened a pull request to add the feature.

**Comment by Zyphrax** [comment]
See pull request https://github.com/DaveWoodCom/XCGLogger/pull/181

**Comment by DaveWoodCom** [comment]
This has finally been added. Now available in 5.0.1. Thanks for your patience with this one!
