### ISSUE TITLE
Error: cannot invoke 'debug' with an argument list of type '(String)'

### ISSUE THREAD

**Issue by mharper** [DaveWoodCom/XCGLogger#67]
Installing `XCGLogger` from the `master` branch using the method in the directions (as a subproject of my Xcode project and then adding dependency/framework) as well as just dragging `XCGLogger.swift` into my project produces the same build error:

```
error: cannot invoke 'debug' with an argument list of type '(String)'
```

In `ApplicationDelegate.swift` in global scope:
```
let log = XCGLogger.defaultInstance()
```
In `application:didFinishLaunchingWithOptions:`:
```
log.setup(logLevel: .Debug, showLogLevel: true, showFileNames: true, showLineNumbers: true, writeToFile: nil)
```

In another Swift file, this line of code inside a method causes the aforementioned build error:

```
log.debug("Message")
```

Xcode Version 6.3.2 (6D2105) building with iOS SDK 8.3

**Comment by DaveWoodCom** [comment]
That should all work, so my guess is there is something else in the file that is causing the compiler to produce that error. Can you show more of the file with the error?

**Comment by mharper** [comment]
I made two mistakes here:

 1. The `log` was initialized in one module but I was attempting to use it in another module (target).
 1. The `XCGLogger.swift` file was not a part of the second target.

I was unable to figure out how to access the `log` across modules, so I've instantiated a new one in the module where I need it.

Everything works fine now. Sorry for the false alarm.
