### ISSUE TITLE
Can't close log file except with deinit

### ISSUE THREAD

**Issue by bstrull** [DaveWoodCom/XCGLogger#69]
The only time the log file (XCGFileLogDestination) gets closed is in the deinit on the XCGFileLogDestination.   I'm trying to allow the user to email the log file to report defects when they occur.  As a workaround, instead of using the defaultInstance which never gets a deinit call, I create my own instance that is an optional so I can set it to nil to force a deinit.  The basic flow

- at app launch, create an XCGLogger and call setup with a log file.
- to email the file, set the XCGLogger to nil, copy the log file to history, and email the history file
- recreate the XCGLogger which start with a new empty log file.

I'm doing the same process when the app enters background to make sure I have a complete log file.

I also think processLogDetails() needs a call to synchronizeFile() at the end to make sure the log file is complete.

**Comment by leolobato** [comment]
This is a big deal.

Maybe exposing `logFileHandle`, or a method which returns a `NSData` object with the current log contents would be the way to go?

**Comment by DaveWoodCom** [comment]
Done.

Changed the `writeToFileURL` property of `XCGFileLogDestination` to public. Setting a new value will close the existing file and reopen a new file at the new location.

Also have added a `rotateFile` method to `XCGFileLogDestination` that will close the existing file, move it to the new location specified, and reopen another file at the old location.
