### ISSUE TITLE
Project update status

### ISSUE THREAD

**Issue by foozmeat** [DaveWoodCom/XCGLogger#77]
The maintainer of XCGLogger @DaveWoodCom hasn't pushed a commit to github in over a month and the issues and pull requests are starting to pile up here. I would like to use XCGLogger in a shipping ios9 project but I'd rather not maintain a private fork.

It would be great if @DaveWoodCom jumped in here and posted an update on where things are headed. If he's too busy to be a maintainer then perhaps he could recruit a few other to take over the management of the pull requests?

I don't want to see this project die a death of a thousand forks.

**Comment by DaveWoodCom** [comment]
With my commitments to client work via MartianCraft, my own apps in development for Cerebral Gardens, and family commitments, there's not a lot of time to give away.

The `master` and `swift_2.0` branches have now had a tonne of updates and should be good to go for a while.

I'm always grateful for pull requests, and always go though them thoroughly to ensure the code works as intended and is as efficient as possible.

Of course, anyone wanting to support the effort could help by buying a copy of my Watchdog for Xcode app: https://itunes.apple.com/us/app/watchdog-for-xcode/id734258109?mt=12&uo=4&at=11lMGu :)

**Comment by foozmeat** [comment]
Thanks Dave, the effort is definitely appreciated.
