### ISSUE TITLE
Naming individual loggers

### ISSUE THREAD

**Issue by zbeckman** [DaveWoodCom/XCGLogger#79]
It would be great if individual logger instances had names, and emitted the name, e.g.:

11:06AM "testing" [Info] [main] [GPLog.swift:91] logger(_:withLevel:withDateFormat:) > testing logger initialized to level Info

This would help identify specific log "threads" in the output. In our system, we actually have seven different loggers for things like ux, security, web requests, core data... and adjust each independently so that we can zoom in on a particular area.

On a side note: I have a small class that loads and configures a set of loggers based on a property list file. Handy way to easily load preconfigured loggers. One logger instance created for each property list entry, with output level specified. If you take a logger out of the property list, then all logging is instead directed to the default logger. Would be great to see this kind of functionality evolve in XCGLogger. Happy to contribute a bit of code if you are interested, too...

**Comment by DaveWoodCom** [comment]
Good idea. Will add this soon. The preconfiguration options is something I'm already looking into, though, wasn't thinking of using plists. I'd be interested to see what you're putting in the plist etc. Is it somehow easier than just using code?

**Comment by DaveWoodCom** [comment]
This has been added. Set the `identifier` of the logger, then Include `showLogIdentifier: true,` in your `setup()` call.

**Comment by zbeckman** [comment]
Awesome, will try out the identifier.

Regarding plists... The main advantage is being able to change configuration without any changes in the code, and hence no need to recompile. It also makes it easy to modify the number of loggers and each one's log level. It's really just a list of logger names and levels. I have a singleton (factory) that reads the plist, creates each logger from the plist, sets the log level, and then later you can get the logger by asking for it by name, e.g.:

```let logger = GPLog.getLogger("testing")```

```logger.debug("my message")```

Happy to contribute the code if you would like. It would be pretty trivial to alter is to be more generic. Would probably add something like an `XCGLogger.load(from: plistFile)` and an `XCGLogger.getLogger(name)` function, plus a little internal mechanics.

**Comment by zbeckman** [comment]
Afterthought – Using a plist is a little bit of a hack, what would probably be ideal is using an XML configuration file much like Logback: http://logback.qos.ch/documentation.html. The plist solution was basically a quick-and-dirty approach to the same and works great for our purposes... but probably is not ideal.

**Comment by DaveWoodCom** [comment]
Ok thanks. Some good food for thought there. I was planning to create some preconfigured options so I'll probably add something like this in the next update. Going to leave this issue open to remind me. :)

**Comment by DaveWoodCom** [comment]
Closing, don't think configuring the logger with an external file adds much benefit. The advanced configuration options can be set up in code and tweaked based on compiler settings if needed.
