### ISSUE TITLE
Accept 'Printable's and 'DebugPrintable's as well as 'String's, like Swift's 'print()'

### ISSUE THREAD

**Issue by mhuusko5** [DaveWoodCom/XCGLogger#80]
XCGLogger is incredibly useful/feature-full, but lacks the basic convenience of Swift's built in 'print()' function because it only accept 'String's. Is there a reason for this I'm missing?

**Comment by DaveWoodCom** [comment]
No reason. Will push an updated version with this fixed soon (probably tonight). Thanks.

**Comment by mhuusko5** [comment]
Awesome!!

**Comment by DaveWoodCom** [comment]
I have this working in a private branch, but it breaks backwards compatibility, so I'm leaving it out for now. Will re-evaluate later.

It should be fairly easy to work around with the current version of XCGLogger, whatever you have that is `Printable` can just be wrapped in a `String` using string interpolation, such as `log.debug("\(NSDate())")`

**Comment by mhuusko5** [comment]
Okeedoke, great tip!

**Comment by hsoi** [comment]
FWIW, we're dealing with similar breakage type isues in our libraries. We figured that as long as Swift 2.0 was going to have some migration and breakage issues, that'd be a fair time to bring in other migration/breakage issues. Something to consider perhaps.

**Comment by psophis** [comment]
I would like to see this change as well. Any news on a new release that might include this?

**Comment by DaveWoodCom** [comment]
This is now in the master branch. You can now log `Any`thing.
