### ISSUE TITLE
new setup call

### ISSUE THREAD

**Issue by appsird** [DaveWoodCom/XCGLogger#82]
In latest Xcode7 beta 6 the following line:

log.setup(logLevel: .Debug, showThreadName: true, showLogLevel: true, showFileNames: true, showLineNumbers: true, writeToFile: "path/to/file", fileLogLevel: .Debug)

now should be:

log.setup(.Debug, showThreadName: true, showLogLevel: true, showFileNames: true, showLineNumbers: true, writeToFile: "path/to/file", fileLogLevel: .Debug)

note the initial logLevel: is removed. Please confirm and update your instructions.

**Comment by DaveWoodCom** [comment]
Fixed, thanks.
