### ISSUE TITLE
Version_3.0b3 with cocopods

### ISSUE THREAD

**Issue by walsht** [DaveWoodCom/XCGLogger#83]
Is there a way to use the Version_3.0b3 with cocopods.  Tried a number of different ways but can get the version 3.x to load. 
```
pod 'XCGLogger', 'Version_3.0b3'
```

**Comment by zbeckman** [comment]
You can grab the Swift 2 development branch, if that's what you are after:

```
pod 'XCGLogger', :git => 'https://github.com/DaveWoodCom/XCGLogger.git', :branch => 'swift_2.0'
```

**Comment by DaveWoodCom** [comment]
Thanks @zbeckman, I don't actually use CocoaPods, so wasn't even sure how it was done.
