### ISSUE TITLE
Why not use print replace NSLog？

### ISSUE THREAD

**Issue by zhengying** [DaveWoodCom/XCGLogger#88]
There is a bug here :
----- log debug---
log.debug("test%20now") here %20 will escaped
print("test%20now")      // here we got raw string

**Comment by schemers** [comment]
In the NSLog-relatedcode:
 
```
NSLog(adjustedText)
```

needs to be changed to:

```
NSLog("%@", adjustedText)
```

**Comment by zhengying** [comment]
@schemers  you are right!  thanks!

**Comment by DaveWoodCom** [comment]
Thanks, fix for this will be pushed shortly.
