### ISSUE TITLE
Unnecessary NSDate objects

### ISSUE THREAD

**Issue by hibento** [DaveWoodCom/XCGLogger#91]
Hi,

I noticed that the date object for a `logln` call gets created, even if the line / output isn't used. In our case this results in over 20.000 unnecessary NSDate objects. At least in our debug configuration (release is fine - compiler optimization?). But even in debug configuration this could be a benefit: I only notice this during a memory warning ;-)

Solution should be easy: Move the `let date` statement just above `logDetails = ...`

     public func logln(logLevel: LogLevel = .Debug, functionName: ...) {
        let date = NSDate()

        var logDetails: XCGLogDetails? = nil
        for logDestination in self.logDestinations {
            if (logDestination.isEnabledForLogLevel(logLevel)) {
                if logDetails == nil {
                    if let logMessage = closure() {
                        logDetails = XCGLogDetails(logLevel: logLevel, date: date, logMessage: logMessage, functionName: functionName, fileName: fileName, lineNumber: lineNumber)
                    }

**Comment by JaviSoto** [comment]
Yeah, the recommended change makes sense to me :+1:

**Comment by hibento** [comment]
Okay, you need a pull request for these changes?

**Comment by DaveWoodCom** [comment]
Nope. I agree and should have an update this weekend.

**Comment by DaveWoodCom** [comment]
Did a quick fix for this issue tonight. On the /master and /xcode_7.1 branches (full release will come later with additional updates).

**Comment by hibento** [comment]
Great, thank you.
