### ISSUE TITLE
Feature request: disable method names

### ISSUE THREAD

**Issue by dirkpostma** [DaveWoodCom/XCGLogger#94]
It's not possible to disable method names, is it? For me, filename is usually enough IMO logging without method names makes it a lot cleaner.

**Comment by dirkpostma** [comment]
Spitting through the code I see it is possible indeed, though the example in the readme does not contain the option. My feature request changes to: request to update readme :-)

**Comment by aksswami** [comment]
@dirkpostma This is already present in readme. Check [Advance Usage] (https://github.com/DaveWoodCom/XCGLogger#advanced-usage).
```swift
systemLogDestination.showFunctionName = false
```
