### ISSUE TITLE
NSLogger Integration

### ISSUE THREAD

**Issue by Domsware** [DaveWoodCom/XCGLogger#95]
[NSLogger](https://github.com/fpillet/NSLogger) have a nice viewer allowing integration with other log tool:
https://github.com/fpillet/NSLogger/wiki/Integration-with-other-products

This could be a really nice with XCGLogger

**Comment by markuswinkler** [comment]
I built a connector for that (with even image support!).
https://github.com/markuswinkler/XCGLoggerNSLoggerConnector

**Comment by DaveWoodCom** [comment]
@markuswinkler Thanks for the connector. I've added a link to your project in the read me.

**Comment by markuswinkler** [comment]
You are very welcome, glad I could add to it. Your logger is fantastic!
