### ISSUE TITLE
Add tvOS support

### ISSUE THREAD

**Issue by jarleif** [DaveWoodCom/XCGLogger#97]
Can you add tvOS Support for CocoaPods? Thanks

**Comment by DaveWoodCom** [comment]
There's already a branch for tvOS, it's the `xcode_7.1` branch here: https://github.com/DaveWoodCom/XCGLogger/tree/xcode_7.1 and it's working fine with the latest beta (I'm using it in the tvOS version of my new Rudoku game: https://itunes.apple.com/app/apple-store/id965105321?pt=17255&ct=github&mt=8&at=11lMGu ).

I don't use cocoapods myself, but according to the docs here: http://guides.cocoapods.org/using/the-podfile.html you can specify a branch to use. Please let me know if that works for you, or if the podfile on that branch needs updating.
