### ISSUE TITLE
call by custom method?

### ISSUE THREAD

**Issue by hengchengfei** [DaveWoodCom/XCGLogger#98]
I want to use by custom method instead of XCGLogger's log,

how should i to do?
 
![2015-10-20 1 21 20](https://cloud.githubusercontent.com/assets/3182964/10598696/b92b729a-772d-11e5-86c5-cd9c5b7913c4.png)

**Comment by DaveWoodCom** [comment]
Sorry, I'm not sure what you're asking, or what you're trying to do.

You definitely don't want to be calling `setup` every time you log a message though. That code doesn't appear to do anything that XCGLogger doesn't already do.
